// Icon lookup over the embedded Lucide set (see icon-set.mjs, generated by
// scripts/build-icon-set.mjs). Same file lives in workers/visual and workers/agent
// because each worker deploys from its own folder; scripts/icon-set.test.mjs
// asserts the two copies are identical.
//
// Lucide's grammar (24px grid, 2px round stroke, no fill) is the "system icon"
// look people associate with Apple/Linear/Vercel UIs; we render it at the stroke
// width Fenix already uses for tab bars (1.8).
import { LUCIDE } from "./icon-set.mjs";

export const ICON_NAMES = Object.freeze(Object.keys(LUCIDE));
export const ICON_COUNT = ICON_NAMES.length;

/** Italian (and a few generic) words → Lucide vocabulary. Stems cover plural/gender. */
const ALIASES = {
  prenotazion: ["calendar-check", "book-marked"], calendar: ["calendar"], calendario: ["calendar"], agenda: ["calendar", "calendar-days"], appuntament: ["calendar-check", "calendar-clock"], data: ["calendar"], oggi: ["calendar"], giorno: ["calendar"], mese: ["calendar"],
  lista: ["list"], elenco: ["list"], righe: ["list"], attivit: ["list-checks", "list-todo"], todo: ["list-todo"],
  aggiung: ["plus", "circle-plus"], nuovo: ["plus"], nuova: ["plus"], piu: ["plus"], croce: ["plus", "x"], chiudi: ["x"], chiudere: ["x"], elimina: ["trash-2"], cestino: ["trash-2"], cancella: ["trash-2"],
  client: ["user", "users"], utent: ["user", "users"], persona: ["user"], profilo: ["user", "circle-user"], omino: ["user"], account: ["circle-user"], team: ["users"], staff: ["users"], gruppo: ["users"], persone: ["users"], dipendent: ["users", "id-card"], paziente: ["user", "heart-pulse"], pazienti: ["users", "heart-pulse"],
  impostazion: ["settings"], ingranaggio: ["settings", "cog"], configur: ["settings"], preferenz: ["sliders-horizontal"], filtro: ["filter"], filtri: ["filter"], ordina: ["arrow-up-down"],
  cerca: ["search"], ricerca: ["search"], lente: ["search"],
  cuore: ["heart"], preferit: ["heart", "star"], amat: ["heart"], like: ["thumbs-up", "heart"],
  carrello: ["shopping-cart"], acquist: ["shopping-bag", "shopping-cart"], ordin: ["shopping-cart", "package"], prodott: ["package", "box"], magazzino: ["warehouse", "package"], scorte: ["boxes"], spedizion: ["truck"], consegn: ["truck", "package-check"],
  statistic: ["chart-bar", "chart-line"], grafic: ["chart-bar", "chart-line", "chart-pie"], numer: ["hash", "chart-bar"], kpi: ["chart-bar"], andament: ["trending-up", "chart-line"], barre: ["chart-bar"], torta: ["chart-pie"], report: ["file-chart-column", "chart-bar"], dashboard: ["layout-dashboard"], cruscotto: ["layout-dashboard", "gauge"],
  home: ["house"], casa: ["house"], inizio: ["house"], principale: ["house"],
  forbic: ["scissors"], taglio: ["scissors"], barbier: ["scissors"], parrucch: ["scissors"], rasoio: ["scissors"],
  orolog: ["clock"], ora: ["clock"], orario: ["clock"], orari: ["clock"], tempo: ["clock", "timer"], timer: ["timer"], cronometro: ["timer"], sveglia: ["alarm-clock"], scadenz: ["calendar-clock", "alarm-clock"], storico: ["history"], cronologia: ["history"],
  campan: ["bell"], notific: ["bell"], avvis: ["bell", "triangle-alert"], allarme: ["siren", "bell-ring"], attenzion: ["triangle-alert"], errore: ["circle-x", "octagon-alert"], info: ["info"], aiuto: ["circle-help", "life-buoy"], domanda: ["circle-help"],
  mappa: ["map", "map-pin"], posizion: ["map-pin"], luogo: ["map-pin"], indirizz: ["map-pin"], pin: ["map-pin"], segnapost: ["map-pin"], navigazion: ["navigation", "compass"], percorso: ["route"], viaggio: ["plane", "route"], aereo: ["plane"], treno: ["train-front"], auto: ["car"], macchina: ["car"], bici: ["bike"], moto: ["bike"],
  fotocamera: ["camera"], foto: ["camera", "image"], camera: ["camera"], scatt: ["camera"], immagin: ["image", "images"], galleria: ["images"], video: ["video", "clapperboard"], film: ["film", "clapperboard"], musica: ["music"], audio: ["volume-2", "headphones"], microfono: ["mic"], cuffie: ["headphones"], altoparlante: ["speaker", "volume-2"], play: ["play"], riproduci: ["play"], pausa: ["pause"], stop: ["square"],
  mail: ["mail"], email: ["mail"], busta: ["mail"], posta: ["mail"], messagg: ["message-circle", "message-square"], chat: ["message-circle"], commenti: ["message-square"], commento: ["message-square"], invia: ["send"], inviare: ["send"],
  telefon: ["phone"], chiam: ["phone"], cornetta: ["phone"], cellulare: ["smartphone"], smartphone: ["smartphone"], tablet: ["tablet"], computer: ["monitor", "laptop"], pc: ["monitor", "laptop"], schermo: ["monitor"],
  stell: ["star"], valutaz: ["star"], rating: ["star"], recension: ["star", "message-square-text"], premio: ["award", "trophy"], trofeo: ["trophy"], medaglia: ["medal", "award"], coppa: ["trophy"], badge: ["badge-check"],
  etichett: ["tag"], prezz: ["tag", "euro"], tag: ["tag"], sconto: ["percent", "badge-percent"], offert: ["tag", "badge-percent"], promozion: ["megaphone", "badge-percent"], coupon: ["ticket-percent"],
  document: ["file-text"], fattur: ["receipt", "file-text"], file: ["file"], foglio: ["file-text", "sheet"], ricevut: ["receipt"], scontrino: ["receipt"], contratto: ["file-signature"], firma: ["pen-line", "file-signature"], cartella: ["folder"], cartelle: ["folder"], archivio: ["archive"], allegato: ["paperclip"], allegati: ["paperclip"], stampa: ["printer"], stampante: ["printer"], pdf: ["file-text"], scarica: ["download"], download: ["download"], carica: ["upload"], upload: ["upload"], esporta: ["file-output", "download"], importa: ["file-input", "upload"], copia: ["copy"], incolla: ["clipboard-paste"], appunti: ["clipboard"], blocco: ["notebook", "clipboard"], nota: ["sticky-note", "notebook-pen"], note: ["sticky-note", "notebook-pen"], matita: ["pencil"], modifica: ["pencil", "square-pen"], penna: ["pen"], evidenziator: ["highlighter"],
  menu: ["menu"], hamburger: ["menu"], altro: ["ellipsis"], opzioni: ["ellipsis-vertical", "settings"], griglia: ["layout-grid"], tabella: ["table"], colonne: ["columns-3"], kanban: ["kanban"], bacheca: ["kanban", "layout-dashboard"],
  soldi: ["banknote", "euro"], denaro: ["banknote"], pagament: ["credit-card", "wallet"], carta: ["credit-card"], portafoglio: ["wallet"], euro: ["euro"], dollar: ["dollar-sign"], banca: ["landmark"], incass: ["hand-coins", "banknote"], spesa: ["shopping-basket", "receipt"], spese: ["receipt", "wallet"], budget: ["piggy-bank", "wallet"], risparmi: ["piggy-bank"], monete: ["coins"], moneta: ["coins"], cassa: ["banknote", "store"], contabilit: ["calculator", "receipt"], calcolatrice: ["calculator"],
  negozio: ["store"], shop: ["store"], vetrina: ["store"], azienda: ["building-2"], ufficio: ["building"], sede: ["building"], edificio: ["building"], fabbrica: ["factory"], hotel: ["hotel", "bed"], albergo: ["hotel", "bed"], camera_letto: ["bed"], letto: ["bed"], ristorante: ["utensils"], cucina: ["chef-hat", "utensils"], menu_cibo: ["utensils"], piatto: ["utensils"], cibo: ["utensils", "pizza"], pizza: ["pizza"], caff: ["coffee"], bar: ["coffee", "beer"], birra: ["beer"], vino: ["wine"], torta_dolce: ["cake"], gelato: ["ice-cream-cone"], dolce: ["cake", "cookie"],
  salute: ["heart-pulse"], medico: ["stethoscope"], dottore: ["stethoscope"], dente: ["stethoscope"], denti: ["stethoscope"], farmac: ["pill"], medicin: ["pill"], ospedale: ["hospital"], clinica: ["hospital"], ambulanza: ["ambulance"], termometro: ["thermometer"], siringa: ["syringe"], cerotto: ["bandage"], fitness: ["dumbbell"], palestra: ["dumbbell"], allenament: ["dumbbell", "activity"], corsa: ["footprints", "activity"], attivita_fisica: ["activity"], battito: ["activity", "heart-pulse"],
  casa_dolce: ["house"], chiave: ["key"], chiavi: ["key-round"], lucchetto: ["lock"], blocca: ["lock"], sblocca: ["lock-open"], password: ["key-round", "lock"], sicurezza: ["shield", "shield-check"], scudo: ["shield"], privacy: ["shield", "eye-off"], protetto: ["shield-check"], verificat: ["badge-check", "circle-check"], occhio: ["eye"], nascondi: ["eye-off"], mostra: ["eye"], visibile: ["eye"],
  login: ["log-in"], accedi: ["log-in"], entra: ["log-in"], esci: ["log-out"], logout: ["log-out"], registrati: ["user-plus"], iscriviti: ["user-plus"], invito: ["user-plus", "mail-plus"],
  salva: ["save"], salvato: ["save", "check"], ok: ["check"], fatto: ["check", "circle-check"], conferma: ["check", "circle-check"], spunta: ["check"], check: ["check"], completat: ["circle-check", "check-check"], annulla: ["x", "undo-2"], indietro: ["arrow-left", "chevron-left"], avanti: ["arrow-right", "chevron-right"], su: ["arrow-up", "chevron-up"], giu: ["arrow-down", "chevron-down"], freccia: ["arrow-right"], frecce: ["arrow-left-right"], aggiorna: ["refresh-cw"], ricarica: ["refresh-cw"], sincronizza: ["refresh-cw"], ripeti: ["repeat"], ripristina: ["rotate-ccw", "undo-2"], condividi: ["share-2", "share"], link: ["link"], collegamento: ["link"], esterno: ["external-link"], apri: ["external-link", "folder-open"], espandi: ["maximize-2"], riduci: ["minimize-2"], schermo_intero: ["maximize"],
  luce: ["sun", "lightbulb"], sole: ["sun"], luna: ["moon"], notte: ["moon"], tema: ["sun-moon", "palette"], scuro: ["moon"], chiaro: ["sun"], colore: ["palette"], colori: ["palette"], pennello: ["brush", "paintbrush"], vernice: ["paint-bucket"], design: ["pen-tool", "palette"], layout: ["layout-template"], componenti: ["component"], meteo: ["cloud-sun"], pioggia: ["cloud-rain"], nuvola: ["cloud"], cloud: ["cloud"], neve: ["snowflake"], vento: ["wind"], fuoco: ["flame"], fiamma: ["flame"], acqua: ["droplet", "droplets"], goccia: ["droplet"], pianta: ["sprout", "leaf"], piante: ["sprout", "leaf"], foglia: ["leaf"], albero: ["tree-pine", "trees"], fiore: ["flower"], fiori: ["flower-2"], giardino: ["shovel", "sprout"], natura: ["leaf", "mountain"], montagna: ["mountain"], mare: ["waves"], spiaggia: ["umbrella", "sun"], terra: ["earth"], mondo: ["globe"], globo: ["globe"], lingua: ["languages"], traduzione: ["languages"],
  cane: ["dog"], gatto: ["cat"], animal: ["paw-print"], zampa: ["paw-print"], veterinari: ["paw-print", "stethoscope"], pesce: ["fish"], uccello: ["bird"], mucca: ["beef"],
  libro: ["book"], libri: ["library", "book-open"], lettura: ["book-open"], biblioteca: ["library"], scuola: ["graduation-cap", "school"], student: ["graduation-cap"], corso: ["graduation-cap", "book-open"], corsi: ["graduation-cap"], lezione: ["presentation"], lezioni: ["presentation"], insegnante: ["presentation"], quiz: ["circle-help", "list-checks"], esame: ["clipboard-check"], laurea: ["graduation-cap"], certificato: ["award", "file-badge"], diploma: ["scroll"],
  lavoro: ["briefcase"], valigetta: ["briefcase"], progetto: ["folder-kanban"], progetti: ["folder-kanban"], task: ["list-todo", "circle-check"], obiettiv: ["target", "goal"], bersaglio: ["target"], traguardo: ["flag", "goal"], bandiera: ["flag"], razzo: ["rocket"], lancio: ["rocket"], idea: ["lightbulb"], lampadina: ["lightbulb"], magia: ["sparkles", "wand-sparkles"], scintill: ["sparkles"], ia: ["sparkles", "bot"], ai: ["sparkles", "bot"], robot: ["bot"], codice: ["code"], sviluppo: ["code", "terminal"], terminale: ["terminal"], database: ["database"], server: ["server"], api: ["webhook", "plug"], integrazion: ["plug", "blocks"], plugin: ["puzzle"], estension: ["puzzle"], bug: ["bug"], test: ["flask-conical", "test-tube"], laboratorio: ["flask-conical"], chimica: ["flask-conical"], scienza: ["atom", "microscope"], microscopio: ["microscope"], ricerca_scienza: ["microscope"],
  strumenti: ["wrench", "hammer"], chiave_inglese: ["wrench"], martello: ["hammer"], riparazion: ["wrench"], manutenzion: ["wrench", "settings"], cacciavite: ["wrench"], costruzion: ["hard-hat", "construction"], cantiere: ["hard-hat"], casco: ["hard-hat"], elettric: ["zap", "plug"], fulmine: ["zap"], batteria: ["battery"], energia: ["zap", "battery-charging"], wifi: ["wifi"], rete: ["network", "wifi"], bluetooth: ["bluetooth"], segnale: ["signal"], gps: ["locate", "map-pin"], satellite: ["satellite"], qr: ["qr-code"], barcode: ["barcode", "scan-barcode"], scanner: ["scan"], scansiona: ["scan-line"], nfc: ["nfc"], impronta: ["fingerprint"], faccia: ["scan-face"], volto: ["scan-face"],
  regalo: ["gift"], regali: ["gift"], festa: ["party-popper"], compleanno: ["cake", "party-popper"], evento: ["calendar", "ticket"], eventi: ["calendar-days", "ticket"], biglietto: ["ticket"], biglietti: ["tickets"], gioco: ["gamepad-2"], giochi: ["gamepad-2"], dado: ["dice-5"], puzzle: ["puzzle"], carte: ["spade", "club"], sport: ["trophy", "dumbbell"], calcio: ["volleyball"], pallone: ["volleyball"], basket: ["trophy"], tennis: ["trophy"], nuoto: ["waves"], yoga: ["heart-pulse"],
  vestit: ["shirt"], maglia: ["shirt"], abbigliament: ["shirt"], scarpe: ["footprints"], moda: ["shirt", "sparkles"], borsa: ["shopping-bag", "handbag"], occhiali: ["glasses"], orologio_polso: ["watch"], anello: ["gem"], gioiell: ["gem"], diamante: ["gem"], corona: ["crown"], bellezza: ["sparkles"], trucco: ["sparkles"], profumo: ["spray-can"], spa: ["flower", "bath"], massaggio: ["hand"], mano: ["hand"], mani: ["hand"],
  bambin: ["baby"], neonat: ["baby"], famiglia: ["users", "house-heart"], genitor: ["users"], anzian: ["accessibility", "user"], accessibilit: ["accessibility"], disabilit: ["accessibility"], sedia: ["armchair"], divano: ["sofa"], tavolo: ["table"], lampada: ["lamp"], cucina_casa: ["cooking-pot"], pentola: ["cooking-pot"], frigo: ["refrigerator"], lavatrice: ["washing-machine"], microonde: ["microwave"], porta: ["door-open"], finestra: ["app-window"], chiavi_casa: ["key-round"], trasloco: ["truck", "package"], pulizia: ["spray-can", "brush-cleaning"], pulizie: ["brush-cleaning", "spray-can"], immobil: ["house", "building-2"], affitto: ["house", "key"], vendita: ["tag", "handshake"], accordo: ["handshake"], stretta: ["handshake"], partner: ["handshake"],
  legge: ["scale", "gavel"], avvocat: ["scale", "gavel"], tribunale: ["gavel", "landmark"], giustizia: ["scale"], bilancia: ["scale"], martelletto: ["gavel"], contratti: ["file-signature"], polizia: ["shield", "siren"], sirena: ["siren"], pompieri: ["flame", "siren"], emergenz: ["siren", "phone-call"],
  volume: ["volume-2"], muto: ["volume-x"], tv: ["tv"], radio: ["radio"], podcast: ["podcast", "mic"], streaming: ["cast", "tv"], trasmetti: ["cast", "radio-tower"], antenna: ["radio-tower"], onda: ["audio-waveform"], onde: ["waves"],
  utente_shield: ["shield-user"], amministrator: ["shield-user", "user-cog"], admin: ["shield-user", "user-cog"], ruolo: ["user-cog"], ruoli: ["users-round", "user-cog"], permessi: ["key-round", "shield-check"], autorizzazion: ["shield-check"],
  cronologia_versioni: ["git-branch"], versione: ["git-commit-horizontal", "tag"], versioni: ["git-branch", "history"], ramo: ["git-branch"], unisci: ["git-merge", "merge"], pubblica: ["upload", "globe", "send"], pubblicat: ["globe", "circle-check"], online: ["globe", "wifi"], offline: ["wifi-off", "cloud-off"], sito: ["globe"], web: ["globe"], browser: ["app-window", "globe"], pagina: ["file", "layout"], pagine: ["files", "book-open"], sezione: ["layout-panel-top"], banner: ["image", "megaphone"], annuncio: ["megaphone"], megafono: ["megaphone"], marketing: ["megaphone", "trending-up"], campagna: ["megaphone", "target"], newsletter: ["mail", "newspaper"], giornale: ["newspaper"], notizie: ["newspaper"], news: ["newspaper"], blog: ["rss", "newspaper"], rss: ["rss"], social: ["share-2", "users"], hashtag: ["hash"], citazione: ["quote"], virgolette: ["quote"], testo: ["type", "text"], font: ["type"], carattere: ["type"], grassetto: ["bold"], corsivo: ["italic"], sottolineato: ["underline"], allinea: ["align-left"], paragrafo: ["pilcrow"], titolo: ["heading"], titoli: ["heading"], elenco_puntato: ["list"], numerato: ["list-ordered"], tabella_dati: ["table-2"],
  casella: ["square-check", "square"], cerchio: ["circle"], quadrato: ["square"], triangolo: ["triangle"], esagono: ["hexagon"], forma: ["shapes"], forme: ["shapes"], punto: ["dot", "circle-dot"], punti: ["ellipsis"], trattino: ["minus"], meno: ["minus"], uguale: ["equal"], percentuale: ["percent"], infinito: ["infinity"], asterisco: ["asterisk"], ancora: ["anchor"], nave: ["ship"], barca: ["sailboat", "ship"], porto: ["anchor"], bussola: ["compass"], binocolo: ["binoculars"], torcia: ["flashlight"], candela: ["flame"], lanterna: ["lamp"], tenda: ["tent"], campeggio: ["tent", "tent-tree"], zaino: ["backpack"], valigia: ["luggage"], bagagli: ["luggage"], passaporto: ["book-user", "id-card"], carta_identit: ["id-card"], tessera: ["id-card", "credit-card"], documento_identit: ["id-card"],
};

/** Multi-word Italian phrases resolved before tokenising. */
const PHRASES = [
  ["chiave inglese", "wrench"], ["carta di credito", "credit-card"], ["carta d'identita", "id-card"], ["carta identita", "id-card"],
  ["schermo intero", "maximize"], ["camera da letto", "bed"], ["attivita fisica", "activity"], ["punto vendita", "store"],
  ["lista della spesa", "shopping-basket"], ["posta elettronica", "mail"], ["codice qr", "qr-code"], ["codice a barre", "barcode"],
  ["elenco puntato", "list"], ["elenco numerato", "list-ordered"], ["tre linee", "menu"], ["tre puntini", "ellipsis"],
  ["segno di spunta", "check"], ["punto interrogativo", "circle-help"], ["punto esclamativo", "circle-alert"],
  ["freccia indietro", "arrow-left"], ["freccia avanti", "arrow-right"], ["cestino dei rifiuti", "trash-2"],
];

const STOP = new Set("il lo la i gli le un uno una di del della dei delle da dal dalla in nel nella su sul sulla per con e o a al alla che come da usa metti cambia sostituisci diventa scegli imposta icona icone tab della la un'icona voglio vorrei mi serve pittogramma simbolo the a an of to for with and or use put set icon icons an".split(" "));

function normalize(s) {
  return String(s || "").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "");
}

function tokens(query) {
  let q = normalize(query);
  for (const [phrase, name] of PHRASES) q = q.split(phrase).join(` ${name} `);
  return q.split(/[^a-z0-9-]+/).filter((t) => t.length > 1 && !STOP.has(t));
}

/** Words derived from one token: itself and Italian aliases whose stem prefixes it. */
function expand(token, preferred) {
  const out = new Set([token]);
  const add = (names) => { names.forEach((n) => out.add(n)); if (preferred) preferred.add(names[0]); };
  if (ALIASES[token]) add(ALIASES[token]);
  for (const [stem, names] of Object.entries(ALIASES)) {
    if (stem.length >= 4 && token.startsWith(stem) && token.length - stem.length <= 3) add(names);
  }
  // English plural → singular (users → user, files → file)
  if (token.length > 4 && token.endsWith("s")) out.add(token.slice(0, -1));
  return [...out];
}

/**
 * Ranks Lucide icons for a free-text query (Italian or English).
 * Returns [{ name, score }] best first, empty when nothing matches.
 */
export function findIcons(query, { limit = 6 } = {}) {
  const preferred = new Set();
  const words = [...new Set(tokens(query).flatMap((t) => expand(t, preferred)))];
  if (!words.length) return [];
  const scores = new Map();
  const bump = (name, n) => scores.set(name, (scores.get(name) || 0) + n);
  for (const w of words) {
    if (LUCIDE[w]) bump(w, preferred.has(w) ? 19 : 18); // exact name; first alias of a word wins ties
  }
  // "map pin" → map-pin outranks map and pin alone
  const joined = words.filter((w) => !w.includes("-")).join("-");
  if (joined.includes("-") && LUCIDE[joined]) bump(joined, 18);
  for (const w of words) {
    if (w.length < 3 || w.includes("-")) continue;
    for (const name of ICON_NAMES) {
      if (name === w) continue;
      const parts = name.split("-");
      if (parts[0] === w) bump(name, 6 - Math.min(parts.length - 1, 3));
      else if (parts.includes(w)) bump(name, 3);
      else {
        const t = LUCIDE[name][1];
        if (t && (` ${t} `).includes(` ${w} `)) bump(name, 2);
      }
    }
  }
  return [...scores.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].length - b[0].length || (a[0] < b[0] ? -1 : 1))
    .slice(0, limit)
    .map(([name, score]) => ({ name, score }));
}

/** Best icon name for a query, or null. Requires a confident match (not a lone tag hit). */
export function iconForQuery(query) {
  const [best] = findIcons(query, { limit: 1 });
  return best && best.score >= 3 ? best.name : null;
}

/** Full <svg> for a Lucide icon, in the stroke grammar Fenix uses for UI chrome. */
export function iconSvg(name, { size = 24, strokeWidth = 1.8, className = "", label = "" } = {}) {
  const entry = LUCIDE[name];
  if (!entry) return "";
  const cls = className ? ` class="${escapeAttr(className)}"` : "";
  const a11y = label ? ` role="img" aria-label="${escapeAttr(label)}"` : ' aria-hidden="true"';
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${Number(size) || 24}" height="${Number(size) || 24}" fill="none" stroke="currentColor" stroke-width="${Number(strokeWidth) || 1.8}" stroke-linecap="round" stroke-linejoin="round" overflow="hidden"${cls}${a11y} data-icon="${escapeAttr(name)}">${entry[0]}</svg>`;
}

/** Inline sprite: <symbol> per icon, use with <svg><use href="#i-calendar"/></svg>. */
export function iconSprite(names, { prefix = "i-" } = {}) {
  const symbols = [...new Set(names)].filter((n) => LUCIDE[n]).map((n) => `<symbol id="${prefix}${escapeAttr(n)}" viewBox="0 0 24 24">${LUCIDE[n][0]}</symbol>`);
  return `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">${symbols.join("")}</svg>`;
}

export function hasIcon(name) {
  return Boolean(LUCIDE[name]);
}

function escapeAttr(s) {
  return String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}
