import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it } from "node:test";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");

describe("focus-visible and worker model", () => {
  it("declares :focus-visible on interactive chrome", () => {
    const css = readFileSync(join(root, "src/styles.css"), "utf8");
    assert.match(css, /:focus-visible/);
    assert.match(css, /a:focus-visible/);
    assert.match(css, /button:focus-visible/);
  });

  it("caps worker polish polls so overlay cannot last ~24 minutes", () => {
    const src = readFileSync(join(root, "src/lib/ai/run-build.ts"), "utf8");
    assert.match(src, /WORKER_POLL_MAX = 30/);
    assert.doesNotMatch(src, /for \(let i = 0; i < 240;/);
    assert.match(src, /export async function resumePolish/);
    assert.match(src, /hasActiveVisualJob/);
    assert.match(src, /visualJobPatch/);
    assert.match(src, /Idempotency-Key/);
    const resume = src.slice(
      src.indexOf("export async function resumePolish"),
      src.indexOf("export async function runBuild"),
    );
    assert.doesNotMatch(resume, /spendCredit/);
    assert.match(resume, /finishPolish/);
    assert.match(resume, /abandonVisualJob/);
    assert.match(resume, /if \(message === JOB_STILL_RUNNING\)/);
    assert.match(resume, /const live = Boolean\(hasActiveVisualJob/);
    assert.match(resume, /uniqueLogs/);
    assert.match(resume, /refundBuildCredit/);
    assert.match(resume, /repairBootFailures/);
    assert.match(resume, /SITE_POLISH_INSTRUCTION/);
    assert.match(src, /mergeUniqueLogs\(prev, job\.log\)/);
    assert.match(src, /r\.status === 404/);
    assert.match(src, /fetched\.state === "missing"/);
    assert.match(src, /if \(refund\) refundBuildCredit\(projectId, refund\)/);
    assert.match(src, /charged = !finishPolish/);
  });

  it("uses grok-build-0.1 on the visual worker with no reasoningEffort", () => {
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    assert.match(worker, /MODEL = "grok-build-0.1"/);
    assert.doesNotMatch(worker, /grok-4\.6/);
    assert.doesNotMatch(worker, /reasoning_effort\s*:/);
    assert.doesNotMatch(worker, /reasoningEffort\s*:/);
    const model = readFileSync(join(root, "src/lib/ai/model.ts"), "utf8");
    assert.match(model, /FENIX_MODEL = "grok-build-0.1"/);
    const edge = readFileSync(join(root, "netlify/edge-functions/build.ts"), "utf8");
    assert.match(edge, /MODEL = "grok-build-0.1"/);
    assert.doesNotMatch(edge, /reasoning_effort/);
  });

  it("does not iframe invalid or error projects on the home cards", () => {
    const card = readFileSync(join(root, "src/components/project-card.tsx"), "utf8");
    assert.match(card, /status === "error"/);
    assert.match(card, /validatePublishable/);
    assert.match(card, /report\?\.syntaxOk/);
    const recover = readFileSync(join(root, "src/lib/projects/recover.ts"), "utf8");
    assert.match(recover, /STALE_BUILD_MS = 120_000/);
    assert.doesNotMatch(recover, /status = "ready"/);
    assert.match(recover, /stripPhoneChromeFromSite/);
    const store = readFileSync(join(root, "src/lib/projects/store.ts"), "utf8");
    assert.match(store, /resolveProjectKind/);
    assert.doesNotMatch(store, /existing\?\.kind \?\? result\.kind/);
    assert.match(store, /kind: ProjectKind = "app"/);
    assert.match(store, /recoverPersistedProject/);
    assert.match(store, /MAX_PROJECTS = 48/);
    assert.match(store, /stripPhoneChromeFromSite/);
    const studio = readFileSync(join(root, "src/routes/studio.$projectId.tsx"), "utf8");
    assert.match(studio, /isPublishable/);
    assert.match(studio, /compact=\{Boolean\(project\.html\)\}/);
    assert.match(studio, /codePaneFiles/);
    assert.doesNotMatch(studio, /fenix2Files\(seedFiveScreens/);
    const sito = readFileSync(join(root, "src/routes/sito.$projectId.tsx"), "utf8");
    assert.doesNotMatch(sito, /useProjectStore/);
    assert.match(sito, /loadPublished/);
    const sitesApi = readFileSync(join(root, "src/routes/api/sites.$id.ts"), "utf8");
    assert.match(sitesApi, /handleSiteRequest/);
    const sitesFn = readFileSync(join(root, "netlify/functions/sites.ts"), "utf8");
    assert.match(sitesFn, /path: "\/api\/sites\/:id"/);
    assert.match(sitesFn, /handleSiteRequest/);
    const sitesHttp = readFileSync(join(root, "src/lib/projects/sites-http.ts"), "utf8");
    assert.match(sitesHttp, /writePublished/);
    assert.match(sitesHttp, /readPublished/);
    assert.match(sitesHttp, /ownerFromRequest/);
    assert.match(sitesHttp, /x-fenix-if-match/);
    const owner = readFileSync(join(root, "src/lib/projects/publish-owner.ts"), "utf8");
    assert.match(owner, /x-fenix-owner/);
    assert.match(owner, /parseIfMatch/);
    const ci = readFileSync(join(root, ".github/workflows/ci.yml"), "utf8");
    assert.match(ci, /playwright install --with-deps chromium/);
    assert.match(ci, /actions\/cache@v4/);
    assert.doesNotMatch(sito, /allow-same-origin/);
    const previewFrame = readFileSync(join(root, "src/components/preview-frame.tsx"), "utf8");
    assert.doesNotMatch(previewFrame, /allow-same-origin/);
    const publishedStore = readFileSync(join(root, "src/lib/projects/published-store.ts"), "utf8");
    assert.match(publishedStore, /@netlify\/blobs/);
    assert.match(publishedStore, /validatePublishable/);
    const panel = readFileSync(join(root, "src/components/publish-panel.tsx"), "utf8");
    assert.match(panel, /publishSnapshot/);
    assert.match(panel, /readPublishedId/);
    const overlay = readFileSync(join(root, "src/components/build-overlay.tsx"), "utf8");
    assert.match(overlay, /compact = false/);
    assert.match(overlay, /z-20/);
    assert.doesNotMatch(overlay, /z-12/);
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    assert.doesNotMatch(worker, /card bianche, panel scuro solo se serve un dato, CTA pillola blu/);
    assert.doesNotMatch(worker, /2 colori #1d1d1f \/ #0071e3/);
    assert.match(worker, /function looksDashboard/);
    assert.match(worker, /function looksSite/);
    assert.match(worker, /k === "site" \|\| k === "landing"/);
    assert.match(worker, /body\.kind/);
    assert.match(worker, /function looksPhoneShell/);
    assert.match(worker, /nodo assente/);
    assert.doesNotMatch(worker, /<template id="t-\$\{tid\}">/);
    assert.match(worker, /DASHBOARD_SYSTEM/);
    assert.match(worker, /SITE_SYSTEM/);
    assert.match(worker, /kind=dashboard/);
    assert.match(worker, /Rifinitura sito \(nav in alto, niente tabbar\)/);
    assert.match(worker, /Layout desktop/);
    assert.match(worker, /function materializeHero/);
    assert.doesNotMatch(worker, /\|\| remote/);
    assert.doesNotMatch(worker, /\|\| hero;/);
    assert.match(worker, /function stripPhoneChromeFromSite/);
    assert.match(worker, /jobsByKey/);
    assert.match(worker, /byKey\.status === "run"/);
    assert.match(worker, /function findReusableJob/);
    assert.match(worker, /activeByProject/);
    assert.match(worker, /idempotency-key/);
    assert.match(worker, /reused: true/);
    assert.match(worker, /function sanitizeIconPack/);
    assert.match(worker, /isAppleChromeSvg/);
    assert.match(worker, /CRAFT_TAB_ICONS/);
    assert.match(worker, /registro a righe/);
  });

  it("drops iOS template fallbacks from look, shell, types and cards", () => {
    const look = readFileSync(join(root, "src/lib/ai/look.ts"), "utf8");
    assert.doesNotMatch(look, /Stile iOS/);
    assert.doesNotMatch(look, /#f5f5f7 #1d1d1f accento #0071e3/);
    const shell = readFileSync(join(root, "src/lib/ai/app-shell.ts"), "utf8");
    assert.doesNotMatch(shell, /#f5f5f7/);
    assert.doesNotMatch(shell, /#0071e3/);
    assert.doesNotMatch(shell, /-apple-system/);
    const types = readFileSync(join(root, "src/lib/projects/types.ts"), "utf8");
    assert.doesNotMatch(types, /#f5f5f7/);
    assert.doesNotMatch(types, /#0071e3/);
    const card = readFileSync(join(root, "src/components/project-card.tsx"), "utf8");
    assert.doesNotMatch(card, /#f5f5f7/);
    const scheme = readFileSync(join(root, "src/lib/projects/color-scheme.ts"), "utf8");
    assert.doesNotMatch(scheme, /#f5f5f7/);
    assert.doesNotMatch(scheme, /#0071e3/);
    assert.match(scheme, /data-fenix-ready/);
    assert.match(scheme, /ready:\s*function/);
    assert.match(scheme, /data-fenix-desk/);
    assert.match(scheme, /max-width:1120px/);
    assert.doesNotMatch(scheme, /max-width:40rem/);
    assert.match(scheme, /nav\.bottom-tab,nav\.fk-tab\{display:none!important\}/);
    assert.match(scheme, /fenix-boot-error/);
    assert.match(scheme, /fenix-boot-ok/);
    assert.match(scheme, /ev\.target !== window/);
    assert.match(scheme, /data-fenix-img/);
    assert.match(scheme, /unhandledrejection/);
    assert.match(scheme, /data-fenix-boot-error/);
    assert.match(scheme, /data-fenix-boot-ok/);
    assert.doesNotMatch(scheme, /sandboxNoise/);
    assert.match(scheme, /memoryStorage/);
    assert.doesNotMatch(scheme, /void window\.localStorage/);
    assert.doesNotMatch(scheme, /defineProperty\(window, "localStorage"/);
    assert.match(scheme, /absolutizeCraftHero/);
    assert.match(look, /waitPreviewBoot/);
    assert.match(look, /rememberBootError/);
    assert.match(look, /rememberBootOk/);
    assert.match(look, /Avvio senza segnale/);
    assert.match(look, /fenix-boot-ok/);
    const crud = readFileSync(join(root, "src/lib/projects/dashboard-crud.ts"), "utf8");
    assert.match(crud, /data-fenix-crud/);
    assert.match(crud, /b85c38/);
    const runBuild = readFileSync(join(root, "src/lib/ai/run-build.ts"), "utf8");
    assert.doesNotMatch(runBuild, /Fenix 2: Vite \+ React/);
    assert.match(runBuild, /BOOT_REPAIR_MAX = 2/);
    assert.match(runBuild, /repairBootFailures/);
    assert.match(runBuild, /waitPreviewBoot/);
    assert.match(runBuild, /getPreviewBootOk/);
    assert.match(runBuild, /polishedOnce/);
    assert.match(runBuild, /Anteprima già rifinita/);
    assert.match(runBuild, /withoutPronto/);
    assert.match(runBuild, /SITE_POLISH_INSTRUCTION/);
    assert.match(runBuild, /if \(!\(instruction \|\| isIOS\(\)\) && phone\)/);
    assert.match(runBuild, /isIOS\(\) \|\| desk/);
    assert.match(runBuild, /GENERATE_POLL_MAX = 360/);
    assert.match(runBuild, /isTransientNetwork/);
    assert.match(runBuild, /throw new Error\(event\.error \|\| "network error"\)/);
    assert.match(runBuild, /proxyAnswered/);
    assert.match(runBuild, /else if \(isIOS\(\) \|\| desk\)/);
    assert.doesNotMatch(runBuild, /alreadyPronto/);
    const buildApi = readFileSync(join(root, "src/routes/api/build.ts"), "utf8");
    assert.match(buildApi, /materializeHero/);
    assert.match(buildApi, /SITE_PROMPT/);
    assert.match(buildApi, /const desk = lockKind === "site"/);
    const prompts = readFileSync(join(root, "src/lib/ai/prompts.shared.ts"), "utf8");
    assert.match(prompts, /export const SITE_PROMPT/);
    assert.match(prompts, /kind":"site"/);
    const qa = readFileSync(join(root, "src/lib/ai/qa.ts"), "utf8");
    assert.match(qa, /isDeskKind\(kind\)\) return null/);
    const suggest = readFileSync(join(root, "src/lib/ai/suggest.ts"), "utf8");
    assert.match(suggest, /Nav in alto: Home, Bottega, Lavori, Visita/);
    assert.match(suggest, /Le cinque tab devono aprire/);
    const hero = readFileSync(join(root, "src/lib/ai/hero-image.ts"), "utf8");
    assert.match(hero, /export async function materializeHero/);
    assert.match(hero, /data:image/);
    assert.match(hero, /this.removeAttribute\('src'\)/);
    assert.match(hero, /fk-tab\|bottom-tab/);
    assert.match(hero, /min\(52vh,560px\)/);
    assert.match(hero, /fk-hero-craft/);
    assert.match(hero, /scrubCraftMedia/);
    assert.match(hero, /injectCraftHero/);
    assert.match(hero, /\/craft-hero\.jpg/);
    assert.match(hero, /CRAFT_HERO_SRC = "\/craft-hero\.jpg"/);
    assert.equal(existsSync(join(root, "public/craft-hero.jpg")), true);
    const storeSrc = readFileSync(join(root, "src/lib/projects/published-store.ts"), "utf8");
    assert.match(storeSrc, /Sito pubblico senza titolare: immutabile/);
    const publishClient = readFileSync(join(root, "src/lib/projects/publish-client.ts"), "utf8");
    assert.match(publishClient, /isLegacyImmutableError/);
    assert.match(publishClient, /randomUUID/);
    assert.match(publishClient, /rememberPublishedId/);
    assert.match(publishClient, /readPublishedId/);
    assert.match(publishClient, /PUBLISHED_MAP_KEY/);
    const sitoSrc = readFileSync(join(root, "src/routes/sito.$projectId.tsx"), "utf8");
    assert.match(sitoSrc, /absolute inset-0/);
    const edge = readFileSync(join(root, "netlify/edge-functions/build.ts"), "utf8");
    assert.match(edge, /SITE_PROMPT/);
    assert.match(edge, /const desk = lockKind === "site"/);
    assert.doesNotMatch(runBuild, /Pronto\. \$\{result\.name\} è in anteprima/);
    const resume = runBuild.slice(
      runBuild.indexOf("export async function resumePolish"),
      runBuild.indexOf("export async function runBuild"),
    );
    assert.match(resume, /repairBootFailures/);
    assert.match(resume, /SITE_POLISH_INSTRUCTION/);
    assert.doesNotMatch(runBuild, /JOB_STILL_RUNNING \|\| \/Riprendi rifinitura/);
    assert.match(runBuild, /if \(workerError === JOB_STILL_RUNNING\)/);
  });

  it("suggests nav in alto for a site, not five phone tabs", async () => {
    const { suggestEdits } = await import("../../lib/ai/suggest.ts");
    const tips = suggestEdits("FORMATO: sito web. kind=site. Bottega Terra", "Bottega Terra");
    assert.equal(tips.some((t) => /cinque tab/i.test(t)), false);
    assert.equal(tips.some((t) => /nav in alto/i.test(t)), true);
    const appTips = suggestEdits("FORMATO: app telefono. kind=app. Taccuino");
    assert.equal(appTips.some((t) => /cinque tab/i.test(t)), true);
  });
});
