import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it } from "node:test";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");

describe("focus-visible and worker model", () => {
  it("declares :focus-visible on interactive chrome", () => {
    const css = readFileSync(join(root, "src/styles.css"), "utf8");
    assert.match(css, /:focus-visible/);
    assert.match(css, /a:focus-visible/);
    assert.match(css, /button:focus-visible/);
  });

  it("caps worker polish polls so overlay cannot last ~24 minutes", () => {
    const src = readFileSync(join(root, "src/lib/ai/run-build.ts"), "utf8");
    assert.match(src, /WORKER_POLL_MAX = 30/);
    assert.doesNotMatch(src, /for \(let i = 0; i < 240;/);
    assert.match(src, /export async function resumePolish/);
    assert.match(src, /hasActiveVisualJob/);
    assert.match(src, /visualJobPatch/);
    assert.match(src, /Idempotency-Key/);
    const resume = src.slice(
      src.indexOf("export async function resumePolish"),
      src.indexOf("export async function runBuild"),
    );
    assert.doesNotMatch(resume, /spendCredit/);
    assert.match(resume, /finishPolish/);
    assert.match(resume, /abandonVisualJob/);
    assert.match(resume, /if \(message === JOB_STILL_RUNNING\)/);
    assert.match(resume, /const live = Boolean\(hasActiveVisualJob/);
    assert.match(resume, /uniqueLogs/);
    assert.match(resume, /refundBuildCredit/);
    assert.match(resume, /repairBootFailures/);
    assert.match(resume, /SITE_POLISH_INSTRUCTION/);
    assert.match(src, /mergeUniqueLogs\(prev, job\.log\)/);
    assert.match(src, /r\.status === 404/);
    assert.match(src, /fetched\.state === "missing"/);
    assert.match(src, /if \(refund\) refundBuildCredit\(projectId, refund\)/);
    assert.match(src, /charged = !finishPolish/);
  });

  it("uses grok-build-0.1 on the visual worker with no reasoningEffort", () => {
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    assert.match(worker, /MODEL = "grok-build-0.1"/);
    assert.doesNotMatch(worker, /grok-4\.6/);
    assert.doesNotMatch(worker, /reasoning_effort\s*:/);
    assert.doesNotMatch(worker, /reasoningEffort\s*:/);
    const model = readFileSync(join(root, "src/lib/ai/model.ts"), "utf8");
    assert.match(model, /FENIX_MODEL = "grok-build-0.1"/);
    const edge = readFileSync(join(root, "netlify/edge-functions/build.ts"), "utf8");
    assert.match(edge, /MODEL = "grok-build-0.1"/);
    assert.doesNotMatch(edge, /reasoning_effort/);
  });

  it("does not iframe invalid or error projects on the home cards", () => {
    const card = readFileSync(join(root, "src/components/project-card.tsx"), "utf8");
    assert.match(card, /status === "error"/);
    assert.match(card, /validatePublishable/);
    assert.match(card, /report\?\.syntaxOk/);
    const recover = readFileSync(join(root, "src/lib/projects/recover.ts"), "utf8");
    assert.match(recover, /STALE_BUILD_MS = 120_000/);
    assert.doesNotMatch(recover, /status = "ready"/);
    assert.match(recover, /stripPhoneChromeFromSite/);
    const store = readFileSync(join(root, "src/lib/projects/store.ts"), "utf8");
    assert.match(store, /resolveProjectKind/);
    assert.doesNotMatch(store, /existing\?\.kind \?\? result\.kind/);
    assert.match(store, /kind: ProjectKind = "app"/);
    assert.match(store, /recoverPersistedProject/);
    assert.match(store, /MAX_PROJECTS = 48/);
    assert.match(store, /stripPhoneChromeFromSite/);
    assert.match(store, /if \(!known\) return/);
    assert.match(store, /restoreRevision/);
    assert.match(store, /commitIfChanged/);
    const studio = readFileSync(join(root, "src/routes/studio.$projectId.tsx"), "utf8");
    assert.match(studio, /isPublishable/);
    assert.match(studio, /compact=\{Boolean\(project\.html\)\}/);
    assert.match(studio, /codePaneFiles/);
    assert.match(studio, /FileTree/);
    assert.match(studio, /VersionsButton/);
    assert.match(studio, /RevisionPanel/);
    assert.doesNotMatch(studio, /fenix2Files\(seedFiveScreens/);
    const versionsUi = readFileSync(join(root, "src/components/revision-panel.tsx"), "utf8");
    assert.match(versionsUi, /Versioni/);
    assert.match(versionsUi, /Ripristina/);
    assert.match(versionsUi, /Cotture precedenti/);
    const treeUi = readFileSync(join(root, "src/components/file-tree.tsx"), "utf8");
    assert.match(treeUi, /role="tree"/);
    assert.match(treeUi, /Albero file/);
    assert.match(treeUi, /min-h-11/);
    const filesSrc = readFileSync(join(root, "src/lib/projects/files.ts"), "utf8");
    assert.match(filesSrc, /export function ingestProjectFiles/);
    assert.match(filesSrc, /authorizedPreviewHtml/);
    assert.match(filesSrc, /utf8Bytes/);
    assert.match(filesSrc, /TextEncoder/);
    assert.match(filesSrc, /dropPhoneScreenFiles/);
    const parseSrc = readFileSync(join(root, "src/lib/ai/parse.ts"), "utf8");
    assert.match(parseSrc, /dropPhoneScreenFiles/);
    assert.doesNotMatch(parseSrc, /!f\.path\.startsWith\("src\/"\)/);
    const zipSrc = readFileSync(join(root, "src/lib/projects/zip.ts"), "utf8");
    assert.match(zipSrc, /export function zipProject/);
    assert.match(zipSrc, /fenix\.json/);
    const publishPanel = readFileSync(join(root, "src/components/publish-panel.tsx"), "utf8");
    assert.match(publishPanel, /zipProject/);
    const sito = readFileSync(join(root, "src/routes/sito.$projectId.tsx"), "utf8");
    assert.doesNotMatch(sito, /useProjectStore/);
    assert.match(sito, /loadPublished/);
    assert.match(sito, /bindPublishedSiteDb/);
    const sitesApi = readFileSync(join(root, "src/routes/api/sites.$id.ts"), "utf8");
    assert.match(sitesApi, /handleSiteRequest/);
    const sitesFn = readFileSync(join(root, "netlify/functions/sites.ts"), "utf8");
    assert.match(sitesFn, /path: "\/api\/sites\/:id"/);
    assert.match(sitesFn, /handleSiteRequest/);
    const sitesHttp = readFileSync(join(root, "src/lib/projects/sites-http.ts"), "utf8");
    assert.match(sitesHttp, /writePublished/);
    assert.match(sitesHttp, /readPublished/);
    assert.match(sitesHttp, /ownerFromRequest/);
    assert.match(sitesHttp, /x-fenix-if-match/);
    const owner = readFileSync(join(root, "src/lib/projects/publish-owner.ts"), "utf8");
    assert.match(owner, /x-fenix-owner/);
    assert.match(owner, /parseIfMatch/);
    const ci = readFileSync(join(root, ".github/workflows/ci.yml"), "utf8");
    assert.match(ci, /playwright install --with-deps chromium/);
    assert.match(ci, /actions\/cache@v4/);
    assert.doesNotMatch(sito, /allow-same-origin/);
    const previewFrame = readFileSync(join(root, "src/components/preview-frame.tsx"), "utf8");
    assert.doesNotMatch(previewFrame, /allow-same-origin/);
    const publishedStore = readFileSync(join(root, "src/lib/projects/published-store.ts"), "utf8");
    assert.match(publishedStore, /@netlify\/blobs/);
    assert.match(publishedStore, /validatePublishable/);
    const panel = readFileSync(join(root, "src/components/publish-panel.tsx"), "utf8");
    assert.match(panel, /publishSnapshot/);
    assert.match(panel, /readPublishedId/);
    const overlay = readFileSync(join(root, "src/components/build-overlay.tsx"), "utf8");
    assert.match(overlay, /compact = false/);
    assert.match(overlay, /z-20/);
    assert.doesNotMatch(overlay, /z-12/);
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    assert.doesNotMatch(worker, /card bianche, panel scuro solo se serve un dato, CTA pillola blu/);
    assert.doesNotMatch(worker, /2 colori #1d1d1f \/ #0071e3/);
    assert.match(worker, /function looksDashboard/);
    assert.match(worker, /function looksSite/);
    assert.match(worker, /k === "site" \|\| k === "landing"/);
    assert.match(worker, /body\.kind/);
    assert.match(worker, /function looksPhoneShell/);
    assert.match(worker, /nodo assente/);
    assert.doesNotMatch(worker, /<template id="t-\$\{tid\}">/);
    assert.match(worker, /DASHBOARD_SYSTEM/);
    assert.match(worker, /SITE_SYSTEM/);
    assert.match(worker, /kind=dashboard/);
    assert.match(worker, /Rifinitura sito \(nav in alto, niente tabbar\)/);
    assert.match(worker, /Layout desktop/);
    assert.match(worker, /function materializeHero/);
    assert.doesNotMatch(worker, /\|\| remote/);
    assert.doesNotMatch(worker, /\|\| hero;/);
    assert.match(worker, /function stripPhoneChromeFromSite/);
    assert.match(worker, /jobsByKey/);
    assert.match(worker, /byKey\.status === "run"/);
    assert.match(worker, /function findReusableJob/);
    assert.match(worker, /activeByProject/);
    assert.match(worker, /idempotency-key/);
    assert.match(worker, /reused: true/);
    assert.match(worker, /function sanitizeIconPack/);
    assert.match(worker, /isAppleChromeSvg/);
    assert.match(worker, /CRAFT_TAB_ICONS/);
    assert.match(worker, /registro a righe/);
  });

  it("drops iOS template fallbacks from look, shell, types and cards", () => {
    const look = readFileSync(join(root, "src/lib/ai/look.ts"), "utf8");
    assert.doesNotMatch(look, /Stile iOS/);
    assert.doesNotMatch(look, /#f5f5f7 #1d1d1f accento #0071e3/);
    const shell = readFileSync(join(root, "src/lib/ai/app-shell.ts"), "utf8");
    assert.doesNotMatch(shell, /#f5f5f7/);
    assert.doesNotMatch(shell, /#0071e3/);
    assert.doesNotMatch(shell, /-apple-system/);
    const types = readFileSync(join(root, "src/lib/projects/types.ts"), "utf8");
    assert.doesNotMatch(types, /#f5f5f7/);
    assert.doesNotMatch(types, /#0071e3/);
    const card = readFileSync(join(root, "src/components/project-card.tsx"), "utf8");
    assert.doesNotMatch(card, /#f5f5f7/);
    const scheme = readFileSync(join(root, "src/lib/projects/color-scheme.ts"), "utf8");
    assert.doesNotMatch(scheme, /#f5f5f7/);
    assert.doesNotMatch(scheme, /#0071e3/);
    assert.match(scheme, /data-fenix-ready/);
    assert.match(scheme, /ready:\s*function/);
    assert.match(scheme, /data-fenix-desk/);
    assert.match(scheme, /max-width:1120px/);
    assert.doesNotMatch(scheme, /max-width:40rem/);
    assert.match(scheme, /nav\.bottom-tab,nav\.fk-tab\{display:none!important\}/);
    assert.match(scheme, /min-height:44px/);
    assert.match(scheme, /:focus-visible/);
    assert.doesNotMatch(scheme, /max-width:32vw/);
    assert.doesNotMatch(scheme, /\.logo,\.brand[^}]*text-overflow:ellipsis/);
    assert.doesNotMatch(scheme, /nav[^}]*flex-wrap:nowrap!important/);
    assert.match(scheme, /fenix-boot-error/);
    assert.match(scheme, /fenix-boot-ok/);
    assert.match(scheme, /ev\.target !== window/);
    assert.match(scheme, /data-fenix-img/);
    assert.match(scheme, /unhandledrejection/);
    assert.match(scheme, /data-fenix-boot-error/);
    assert.match(scheme, /data-fenix-boot-ok/);
    assert.doesNotMatch(scheme, /sandboxNoise/);
    assert.match(scheme, /memoryStorage/);
    assert.doesNotMatch(scheme, /void window\.localStorage/);
    assert.doesNotMatch(scheme, /defineProperty\(window, "localStorage"/);
    assert.match(scheme, /absolutizeCraftHero/);
    assert.match(look, /waitPreviewBoot/);
    assert.match(look, /rememberBootError/);
    assert.match(look, /rememberBootOk/);
    assert.match(look, /Avvio senza segnale/);
    assert.match(look, /fenix-boot-ok/);
    const crud = readFileSync(join(root, "src/lib/projects/dashboard-crud.ts"), "utf8");
    assert.match(crud, /data-fenix-crud/);
    assert.match(crud, /b85c38/);
    const runBuild = readFileSync(join(root, "src/lib/ai/run-build.ts"), "utf8");
    assert.doesNotMatch(runBuild, /Fenix 2: Vite \+ React/);
    assert.match(runBuild, /BOOT_REPAIR_MAX = 2/);
    assert.match(runBuild, /repairBootFailures/);
    assert.match(runBuild, /waitPreviewBoot/);
    assert.match(runBuild, /getPreviewBootOk/);
    assert.match(runBuild, /polishedOnce/);
    assert.match(runBuild, /Anteprima già rifinita/);
    assert.match(runBuild, /withoutPronto/);
    assert.match(runBuild, /SITE_POLISH_INSTRUCTION/);
    assert.match(runBuild, /if \(!\(instruction \|\| isIOS\(\)\) && phone\)/);
    assert.match(runBuild, /isIOS\(\) \|\| desk/);
    assert.match(runBuild, /GENERATE_POLL_MAX = 360/);
    assert.match(runBuild, /isTransientNetwork/);
    assert.match(runBuild, /throw new Error\(event\.error \|\| "network error"\)/);
    assert.match(runBuild, /proxyAnswered/);
    assert.match(runBuild, /else if \(isIOS\(\) \|\| desk\)/);
    assert.doesNotMatch(runBuild, /alreadyPronto/);
    const buildApi = readFileSync(join(root, "src/routes/api/build.ts"), "utf8");
    assert.match(buildApi, /materializeHero/);
    assert.match(buildApi, /SITE_PROMPT/);
    assert.match(buildApi, /const desk = lockKind === "site"/);
    const prompts = readFileSync(join(root, "src/lib/ai/prompts.shared.ts"), "utf8");
    assert.match(prompts, /export const SITE_PROMPT/);
    assert.match(prompts, /kind":"site"/);
    const qa = readFileSync(join(root, "src/lib/ai/qa.ts"), "utf8");
    assert.match(qa, /isDeskKind\(kind\)\) return null/);
    const suggest = readFileSync(join(root, "src/lib/ai/suggest.ts"), "utf8");
    assert.match(suggest, /Nav in alto: Home, Bottega, Lavori, Visita/);
    assert.match(suggest, /Le cinque tab devono aprire/);
    const hero = readFileSync(join(root, "src/lib/ai/hero-image.ts"), "utf8");
    assert.match(hero, /export async function materializeHero/);
    assert.match(hero, /data:image/);
    assert.match(hero, /this.removeAttribute\('src'\)/);
    assert.match(hero, /fk-tab\|bottom-tab/);
    assert.match(hero, /min\(52vh,560px\)/);
    assert.match(hero, /fk-hero-craft/);
    assert.match(hero, /scrubCraftMedia/);
    assert.match(hero, /injectCraftHero/);
    assert.match(hero, /\/craft-hero\.jpg/);
    assert.match(hero, /CRAFT_HERO_SRC = "\/craft-hero\.jpg"/);
    assert.equal(existsSync(join(root, "public/craft-hero.jpg")), true);
    for (const file of ["craft-shelf.jpg", "craft-vase.jpg", "craft-bowl.jpg", "craft-plate.jpg", "craft-pitcher.jpg"]) {
      assert.equal(existsSync(join(root, "public", file)), true, file);
    }
    const storeSrc = readFileSync(join(root, "src/lib/projects/published-store.ts"), "utf8");
    assert.match(storeSrc, /Sito pubblico senza titolare: immutabile/);
    const publishClient = readFileSync(join(root, "src/lib/projects/publish-client.ts"), "utf8");
    assert.match(publishClient, /isLegacyImmutableError/);
    assert.match(publishClient, /randomUUID/);
    assert.match(publishClient, /rememberPublishedId/);
    assert.match(publishClient, /readPublishedId/);
    assert.match(publishClient, /resolvePublishedId/);
    assert.match(publishClient, /PUBLISHED_MAP_KEY/);
    const sitoSrc = readFileSync(join(root, "src/routes/sito.$projectId.tsx"), "utf8");
    assert.match(sitoSrc, /absolute inset-0/);
    const edge = readFileSync(join(root, "netlify/edge-functions/build.ts"), "utf8");
    assert.match(edge, /SITE_PROMPT/);
    assert.match(edge, /const desk = lockKind === "site"/);
    assert.doesNotMatch(runBuild, /Pronto\. \$\{result\.name\} è in anteprima/);
    const resume = runBuild.slice(
      runBuild.indexOf("export async function resumePolish"),
      runBuild.indexOf("export async function runBuild"),
    );
    assert.match(resume, /repairBootFailures/);
    assert.match(resume, /SITE_POLISH_INSTRUCTION/);
    assert.doesNotMatch(runBuild, /JOB_STILL_RUNNING \|\| \/Riprendi rifinitura/);
    assert.match(runBuild, /if \(workerError === JOB_STILL_RUNNING\)/);
    const releaseClient = readFileSync(join(root, "src/lib/release/client.ts"), "utf8");
    const releasePanel = readFileSync(join(root, "src/components/publish-panel.tsx"), "utf8");
    const releaseSecrets = readFileSync(join(root, "src/lib/release/secrets.server.ts"), "utf8");
    const releaseHttp = readFileSync(join(root, "src/lib/release/http.ts"), "utf8");
    const releaseEngine = readFileSync(join(root, "src/lib/release/engine.ts"), "utf8");
    const releaseFn = readFileSync(join(root, "netlify/functions/release.ts"), "utf8");
    assert.match(releasePanel, /startRelease/);
    assert.match(releasePanel, /loadReleaseJob/);
    assert.match(releasePanel, /job\.status !== "run"/);
    assert.match(releasePanel, /App Store Connect/);
    assert.match(releasePanel, /TestFlight/);
    assert.doesNotMatch(releasePanel, /secrets\.server/);
    assert.doesNotMatch(releasePanel, /APPLE_PRIVATE_KEY/);
    assert.doesNotMatch(releasePanel, /BEGIN PRIVATE KEY/);
    assert.doesNotMatch(releaseClient, /process\.env/);
    assert.doesNotMatch(releaseClient, /secrets\.server/);
    assert.match(releaseSecrets, /APPLE_PRIVATE_KEY/);
    assert.match(releaseSecrets, /GOOGLE_PLAY_SERVICE_ACCOUNT/);
    assert.match(releaseSecrets, /APPLE_TEAM_ID/);
    assert.match(releaseSecrets, /ANDROID_KEYSTORE_PATH/);
    assert.match(releaseSecrets, /ANDROID_KEYSTORE_BASE64/);
    assert.match(releaseSecrets, /ANDROID_KEY_ALIAS/);
    assert.match(releaseHttp, /handleReleaseCollection/);
    assert.match(releaseEngine, /gateHtml/);
    assert.match(releaseEngine, /claimReleaseKey/);
    assert.match(releaseEngine, /withLease/);
    assert.match(releaseEngine, /result\.reconciled/);
    assert.match(releaseEngine, /jobIdFromKey/);
    assert.match(releaseEngine, /createsInflight/);
    assert.match(releaseEngine, /asHexKey/);
    assert.match(releaseFn, /path: "\/api\/release"/);
    const storeApi = readFileSync(join(root, "src/lib/release/store-api.ts"), "utf8");
    assert.match(storeApi, /applePreflight/);
    assert.match(storeApi, /googlePreflight/);
    assert.doesNotMatch(releaseClient, /store-api/);
    assert.doesNotMatch(releasePanel, /store-api/);
    const storeSrcRel = readFileSync(join(root, "src/lib/release/store.ts"), "utf8");
    assert.match(storeSrcRel, /claimReleaseKey/);
    assert.match(storeSrcRel, /flag: "wx"/);
    assert.match(storeSrcRel, /ON CONFLICT \(idempotency_key\)/);
    assert.match(storeSrcRel, /createReleaseStore/);
    const migrationRel = readFileSync(join(root, "migrations/0002_release_jobs.sql"), "utf8");
    assert.match(migrationRel, /create table if not exists release_jobs/);
    assert.match(migrationRel, /idempotency_key text not null unique/);
    const iosSrc = readFileSync(join(root, "src/lib/release/ios.ts"), "utf8");
    assert.match(iosSrc, /xcodebuild/);
    assert.match(iosSrc, /altool/);
    assert.match(iosSrc, /appleListLatestBuild/);
    assert.match(iosSrc, /withAppleApiKey/);
    assert.match(iosSrc, /allowProvisioningUpdates|authenticationKeyPath|withIosCodeSign/);
    const appleKeySrc = readFileSync(join(root, "src/lib/release/apple-key.ts"), "utf8");
    assert.match(appleKeySrc, /API_PRIVATE_KEYS_DIR/);
    assert.match(appleKeySrc, /AuthKey_/);
    assert.match(appleKeySrc, /withIosCodeSign/);
    const nativeSrc = readFileSync(join(root, "src/lib/release/native.ts"), "utf8");
    assert.match(nativeSrc, /isa = PBXNativeTarget/);
    assert.match(nativeSrc, /xmlns:android/);
    assert.doesNotMatch(nativeSrc, /\/\/ Generated Fenix iOS wrapper/);
    const androidSrc = readFileSync(join(root, "src/lib/release/android.ts"), "utf8");
    assert.match(androidSrc, /bundleRelease/);
    assert.match(androidSrc, /jarsigner/);
    assert.match(androidSrc, /-keystore/);
    assert.match(androidSrc, /keystoreBase64|withAndroidKeystore/);
    assert.match(androidSrc, /playInsertEdit/);
    assert.match(androidSrc, /playUploadBundle/);
    assert.match(androidSrc, /playCommitInternal/);
    assert.match(androidSrc, /inflight === "play-commit"/);
    const webSrc = readFileSync(join(root, "src/lib/release/web.ts"), "utf8");
    assert.match(webSrc, /netlifyFindOrCreateSite/);
    assert.match(webSrc, /netlifyListDeploys/);
    assert.match(webSrc, /netlifyCreateDeploy/);
    assert.match(webSrc, /netlifyGetDeploy/);
    assert.match(webSrc, /liveUrl|ssl_url/);
    const dispatchSrc = readFileSync(join(root, "src/lib/release/dispatch.ts"), "utf8");
    assert.match(dispatchSrc, /shouldDispatchNative/);
    assert.match(dispatchSrc, /workflow_dispatch|release-ios.yml/);
    assert.match(dispatchSrc, /workflowRunId/);
    assert.match(dispatchSrc, /step: "pipeline"/);
    const deployApi = readFileSync(join(root, "src/lib/release/deploy-api.ts"), "utf8");
    assert.match(deployApi, /edits\/.+\/tracks\/internal|\/edits\/" \+|encodeURIComponent\(edit.id\)/);
    assert.doesNotMatch(
      deployApi.slice(deployApi.indexOf("export async function playGetInternalTrack")),
      /applications\/" \+\s*encodeURIComponent\(packageName\) \+\s*"\/tracks\/internal"/,
    );
    const runnerSrc = readFileSync(join(root, "src/lib/release/runner.ts"), "utf8");
    assert.match(runnerSrc, /fixtureCommand/);
    assert.match(runnerSrc, /xcodebuild/);
    const netlifyToml = readFileSync(join(root, "netlify.toml"), "utf8");
    assert.match(netlifyToml, /sync-static-publish\.mjs/);
    assert.match(netlifyToml, /publish = "\.output\/public"/);
    assert.doesNotMatch(netlifyToml, /publish = "dist"/);
    const pkgJson = readFileSync(join(root, "package.json"), "utf8");
    assert.match(pkgJson, /sync-static-publish\.mjs/);
    const envExample = readFileSync(join(root, ".env.example"), "utf8");
    assert.match(envExample, /APPLE_ISSUER_ID=/);
    assert.match(envExample, /APPLE_TEAM_ID=/);
    assert.match(envExample, /ANDROID_KEYSTORE_PATH=/);
    assert.match(envExample, /ANDROID_KEYSTORE_BASE64=/);
    assert.match(envExample, /ANDROID_KEY_ALIAS=/);
    assert.match(envExample, /FENIX_RELEASE_CALLBACK_SECRET=/);
    assert.doesNotMatch(envExample, /BEGIN PRIVATE KEY/);
    const clientRoots = [join(root, "dist/assets"), join(root, ".output/public/assets")];
    for (const dir of clientRoots) {
      if (!existsSync(dir)) continue;
      for (const name of readdirSync(dir)) {
        if (!/\.(js|mjs|css|html)$/.test(name)) continue;
        const text = readFileSync(join(dir, name), "utf8");
        assert.doesNotMatch(text, /APPLE_PRIVATE_KEY/, name);
        assert.doesNotMatch(text, /BEGIN PRIVATE KEY/, name);
        assert.doesNotMatch(text, /GOOGLE_PLAY_SERVICE_ACCOUNT/, name);
        assert.doesNotMatch(text, /secrets\.server/, name);
      }
    }
    const modelSrc = readFileSync(join(root, "src/lib/ai/model.ts"), "utf8");
    assert.match(modelSrc, /FENIX_MODEL = "grok-build-0.1"/);
    assert.doesNotMatch(modelSrc, /reasoningEffort/);
  });

  it("suggests nav in alto for a site, not five phone tabs", async () => {
    const { suggestEdits } = await import("../../lib/ai/suggest.ts");
    const tips = suggestEdits("FORMATO: sito web. kind=site. Bottega Terra", "Bottega Terra");
    assert.equal(tips.some((t) => /cinque tab/i.test(t)), false);
    assert.equal(tips.some((t) => /nav in alto/i.test(t)), true);
    const appTips = suggestEdits("FORMATO: app telefono. kind=app. Taccuino");
    assert.equal(appTips.some((t) => /cinque tab/i.test(t)), true);
  });

  it("rescues leaked phone-kit CSS and refuses to publish the dump", () => {
    const scheme = readFileSync(join(root, "src/lib/projects/color-scheme.ts"), "utf8");
    assert.match(scheme, /export function looksLikeLeakedCss/);
    assert.match(scheme, /export function repairLeakedCss/);
    assert.match(scheme, /export function looksLikeCssDump/);
    assert.match(scheme, /data-fenix-rescued/);
    assert.match(scheme, /next = repairLeakedCss\(next\)/);
    assert.match(scheme, /\\u0026lt;\\\/\?style/);
    const validate = readFileSync(join(root, "src/lib/projects/validate-html.ts"), "utf8");
    assert.match(validate, /CSS tecnico visibile/);
    assert.match(validate, /looksLikeLeakedCss/);
    const recover = readFileSync(join(root, "src/lib/projects/recover.ts"), "utf8");
    assert.match(recover, /repairLeakedCss/);
    const store = readFileSync(join(root, "src/lib/projects/store.ts"), "utf8");
    assert.match(store, /repairLeakedCss/);
    const files = readFileSync(join(root, "src/lib/projects/files.ts"), "utf8");
    assert.match(files, /!looksLikeLeakedCss\(main\)/);
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    assert.match(worker, /function looksLikeCssDump/);
    assert.match(worker, /if \(looksLikeCssDump\(inner\)\) return html/);
    assert.match(worker, /if \(looksLikeCssDump\(m\[1\]\)\) return html/);
    assert.equal(existsSync(join(root, "src/lib/projects/fixtures/leaked-phone-css.html")), true);
    const leaked = readFileSync(join(root, "src/lib/projects/fixtures/leaked-phone-css.html"), "utf8");
    assert.match(leaked, /\.fk-hello\{/);
    assert.match(leaked, /\.fk-tab,/);
    assert.match(leaked, /\.fk-sheet\{/);
    assert.match(leaked, /<main class="fk-main"/);
  });

  it("github export is server-only GitHub App, ZIP stays, no parity claim", () => {
    const client = readFileSync(join(root, "src/lib/github/client.ts"), "utf8");
    const panel = readFileSync(join(root, "src/components/export-panel.tsx"), "utf8");
    const studio = readFileSync(join(root, "src/routes/studio.$projectId.tsx"), "utf8");
    const api = readFileSync(join(root, "src/lib/github/api.ts"), "utf8");
    const types = readFileSync(join(root, "src/lib/github/types.ts"), "utf8");
    const jwt = readFileSync(join(root, "src/lib/github/jwt.ts"), "utf8");
    const secrets = readFileSync(join(root, "src/lib/github/secrets.server.ts"), "utf8");
    const http = readFileSync(join(root, "src/lib/github/http.ts"), "utf8");
    const refs = readFileSync(join(root, "src/lib/github/references.md"), "utf8");
    const envExample = readFileSync(join(root, ".env.example"), "utf8");
    const fn = readFileSync(join(root, "netlify/functions/github.ts"), "utf8");
    const fnExport = readFileSync(join(root, "netlify/functions/github-export.ts"), "utf8");
    const gap = readFileSync(join(root, "src/lib/projects/fase3-gap.ts"), "utf8");
    assert.doesNotMatch(client, /secrets\.server/);
    assert.doesNotMatch(client, /GITHUB_APP_PRIVATE_KEY/);
    assert.doesNotMatch(client, /process\.env/);
    assert.doesNotMatch(panel, /secrets\.server/);
    assert.doesNotMatch(panel, /GITHUB_APP_PRIVATE_KEY/);
    assert.match(panel, /GitHub non configurato/);
    assert.match(panel, /Scarica \.zip/);
    assert.match(panel, /Connetti GitHub/);
    assert.match(studio, /ExportPanel/);
    assert.match(studio, /aria-label="Esporta"/);
    assert.match(api, /force: false/);
    assert.match(api, /GITHUB_API_VERSION/);
    assert.match(types, /2026-03-10/);
    assert.match(jwt, /RS256/);
    assert.match(jwt, /now - 60/);
    assert.match(secrets, /GITHUB_APP_PRIVATE_KEY/);
    assert.match(http, /GitHub non configurato/);
    assert.match(fn, /path: "\/api\/github"/);
    assert.match(fnExport, /path: "\/api\/github\/export"/);
    assert.match(envExample, /GITHUB_APP_ID=/);
    assert.match(envExample, /GITHUB_APP_SLUG=/);
    assert.doesNotMatch(envExample, /VITE_GITHUB/);
    assert.match(refs, /2026-03-10/);
    assert.match(refs, /force/);
    assert.match(gap, /github-export/);
    assert.match(gap, /GitHub App server-only/);
    assert.doesNotMatch(gap, /feature-complete|uguale a Emergent/);
    const clientRoots = [join(root, "dist/assets"), join(root, ".output/public/assets")];
    for (const dir of clientRoots) {
      if (!existsSync(dir)) continue;
      for (const name of readdirSync(dir)) {
        if (!/\.(js|mjs|css|html)$/.test(name)) continue;
        const text = readFileSync(join(dir, name), "utf8");
        assert.doesNotMatch(text, /GITHUB_APP_PRIVATE_KEY/, name);
        assert.doesNotMatch(text, /VITE_GITHUB/, name);
      }
    }
  });
});
