import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it } from "node:test";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");

describe("focus-visible and worker model", () => {
  it("declares :focus-visible on interactive chrome", () => {
    const css = readFileSync(join(root, "src/styles.css"), "utf8");
    assert.match(css, /:focus-visible/);
    assert.match(css, /a:focus-visible/);
    assert.match(css, /button:focus-visible/);
  });

  it("caps worker polish polls so overlay cannot last ~24 minutes", () => {
    const src = readFileSync(join(root, "src/lib/ai/run-build.ts"), "utf8");
    assert.match(src, /WORKER_POLL_MAX = 30/);
    assert.doesNotMatch(src, /for \(let i = 0; i < 240;/);
    assert.match(src, /export async function resumePolish/);
    assert.match(src, /hasActiveVisualJob/);
    assert.match(src, /visualJobPatch/);
    assert.match(src, /Idempotency-Key/);
    const resume = src.slice(
      src.indexOf("export async function resumePolish"),
      src.indexOf("export async function runBuild"),
    );
    assert.doesNotMatch(resume, /spendCredit/);
    assert.match(resume, /finishPolish/);
    assert.match(resume, /abandonVisualJob/);
    assert.match(resume, /if \(message === JOB_STILL_RUNNING\)/);
    assert.match(resume, /abandonVisualJob\(projectId, RESUME_ERROR\)/);
    assert.match(resume, /const live = Boolean\(hasActiveVisualJob/);
    assert.match(resume, /uniqueLogs/);
    assert.match(resume, /refundBuildCredit/);
    assert.match(resume, /repairBootFailures/);
    assert.match(resume, /SITE_POLISH_INSTRUCTION/);
    assert.match(src, /mergeUniqueLogs\(prev, job\.log\)/);
    assert.match(src, /r\.status === 404/);
    assert.match(src, /fetched\.state === "missing"/);
    assert.match(src, /if \(refund\) refundBuildCredit\(projectId, refund\)/);
    assert.match(src, /charged = !finishPolish/);
  });

  it("uses grok-build-0.1 on the visual worker with no reasoningEffort", () => {
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    assert.match(worker, /MODEL = "grok-build-0.1"/);
    assert.doesNotMatch(worker, /grok-4\.6/);
    assert.doesNotMatch(worker, /reasoning_effort\s*:/);
    assert.doesNotMatch(worker, /reasoningEffort\s*:/);
    const model = readFileSync(join(root, "src/lib/ai/model.ts"), "utf8");
    assert.match(model, /FENIX_MODEL = "grok-build-0.1"/);
    const edge = readFileSync(join(root, "netlify/edge-functions/build.ts"), "utf8");
    assert.match(edge, /MODEL = "grok-build-0.1"/);
    assert.doesNotMatch(edge, /reasoning_effort/);
    const dataApi = readFileSync(join(root, "src/lib/projects/fenix-data-api.ts"), "utf8");
    const collection = readFileSync(join(root, "src/lib/projects/fenix-collection.ts"), "utf8");
    const prompts = readFileSync(join(root, "src/lib/ai/prompts.shared.ts"), "utf8");
    assert.match(dataApi, /dataTokenRe = \/\^\[A-Za-z0-9\._-\]\{1,80\}\$\//);
    assert.match(collection, /FENIX_COLLECTION_RE = \/\^\[A-Za-z0-9\._-\]\{1,80\}\$\//);
    assert.match(collection, /rewriteFenixCollections/);
    assert.match(collection, /canonicalFenixCollection/);
    assert.match(prompts, /A-Za-z0-9\._-\]\{1,80\}/);
    assert.match(prompts, /capi vesti/);
    const adapter = readFileSync(join(root, "src/lib/projects/fenix-adapter.ts"), "utf8");
    const scheme = readFileSync(join(root, "src/lib/projects/color-scheme.ts"), "utf8");
    const store = readFileSync(join(root, "src/lib/projects/store.ts"), "utf8");
    assert.match(adapter, /rewriteFenixCollections/);
    assert.match(scheme, /rewriteFenixCollections/);
    assert.match(store, /rewriteFenixCollections/);
    assert.match(worker, /extraTried/);
    assert.match(worker, /resolvePatchTarget/);
    assert.match(worker, /shouldPolishTab/);
  });

  it("does not iframe invalid or error projects on the home cards", () => {
    const card = readFileSync(join(root, "src/components/project-card.tsx"), "utf8");
    assert.match(card, /status === "error"/);
    assert.match(card, /validatePublishable/);
    assert.match(card, /report\?\.syntaxOk/);
    const recover = readFileSync(join(root, "src/lib/projects/recover.ts"), "utf8");
    assert.match(recover, /STALE_BUILD_MS = 120_000/);
    assert.doesNotMatch(recover, /status = "ready"/);
    assert.match(recover, /stripPhoneChromeFromSite/);
    const store = readFileSync(join(root, "src/lib/projects/store.ts"), "utf8");
    assert.match(store, /resolveProjectKind/);
    assert.doesNotMatch(store, /existing\?\.kind \?\? result\.kind/);
    assert.match(store, /kind: ProjectKind = "app"/);
    assert.match(store, /recoverPersistedProject/);
    assert.match(store, /MAX_PROJECTS = 48/);
    assert.match(store, /stripPhoneChromeFromSite/);
    assert.match(store, /if \(!known\) return/);
    assert.match(store, /restoreRevision/);
    assert.match(store, /commitIfChanged/);
    const studio = readFileSync(join(root, "src/routes/studio.$projectId.tsx"), "utf8");
    assert.match(studio, /isPublishable/);
    assert.match(studio, /isStudioLocked/);
    assert.match(studio, /data-studio-lock/);
    assert.match(studio, /aria-busy/);
    assert.match(studio, /fieldset disabled=\{building \|\| emptyCredits\}/);
    assert.doesNotMatch(studio, /compact=\{Boolean\(project\.html\)\}/);
    assert.match(studio, /codePaneFiles/);
    assert.match(studio, /FileTree/);
    assert.match(studio, /VersionsButton/);
    assert.match(studio, /RevisionPanel/);
    assert.doesNotMatch(studio, /fenix2Files\(seedFiveScreens/);
    const versionsUi = readFileSync(join(root, "src/components/revision-panel.tsx"), "utf8");
    assert.match(versionsUi, /Versioni/);
    assert.match(versionsUi, /Ripristina/);
    assert.match(versionsUi, /Cotture precedenti/);
    const treeUi = readFileSync(join(root, "src/components/file-tree.tsx"), "utf8");
    assert.match(treeUi, /role="tree"/);
    assert.match(treeUi, /Albero file/);
    assert.match(treeUi, /min-h-11/);
    const filesSrc = readFileSync(join(root, "src/lib/projects/files.ts"), "utf8");
    assert.match(filesSrc, /export function ingestProjectFiles/);
    assert.match(filesSrc, /authorizedPreviewHtml/);
    assert.match(filesSrc, /utf8Bytes/);
    assert.match(filesSrc, /TextEncoder/);
    assert.match(filesSrc, /dropPhoneScreenFiles/);
    const parseSrc = readFileSync(join(root, "src/lib/ai/parse.ts"), "utf8");
    assert.match(parseSrc, /dropPhoneScreenFiles/);
    assert.doesNotMatch(parseSrc, /!f\.path\.startsWith\("src\/"\)/);
    const zipSrc = readFileSync(join(root, "src/lib/projects/zip.ts"), "utf8");
    assert.match(zipSrc, /export function zipProject/);
    assert.match(zipSrc, /fenix\.json/);
    const publishPanel = readFileSync(join(root, "src/components/publish-panel.tsx"), "utf8");
    assert.match(publishPanel, /zipProject/);
    assert.match(publishPanel, /authorizedPreviewHtml/);
    assert.match(publishPanel, /html: publishedHtml/);
    const sito = readFileSync(join(root, "src/routes/sito.$projectId.tsx"), "utf8");
    assert.doesNotMatch(sito, /useProjectStore/);
    assert.match(sito, /loadPublished/);
    assert.match(sito, /bindPublishedSiteDb/);
    const sitesApi = readFileSync(join(root, "src/routes/api/sites.$id.ts"), "utf8");
    assert.match(sitesApi, /handleSiteRequest/);
    const sitesFn = readFileSync(join(root, "netlify/functions/sites.ts"), "utf8");
    assert.match(sitesFn, /path: "\/api\/sites\/:id"/);
    assert.match(sitesFn, /handleSiteRequest/);
    const sitesHttp = readFileSync(join(root, "src/lib/projects/sites-http.ts"), "utf8");
    assert.match(sitesHttp, /writePublished/);
    assert.match(sitesHttp, /readPublished/);
    assert.match(sitesHttp, /ownerFromRequest/);
    assert.match(sitesHttp, /x-fenix-if-match/);
    const owner = readFileSync(join(root, "src/lib/projects/publish-owner.ts"), "utf8");
    assert.match(owner, /x-fenix-owner/);
    assert.match(owner, /parseIfMatch/);
    const ci = readFileSync(join(root, ".github/workflows/ci.yml"), "utf8");
    assert.match(ci, /playwright install --with-deps chromium/);
    assert.match(ci, /actions\/cache@v4/);
    assert.doesNotMatch(sito, /allow-same-origin/);
    const previewFrame = readFileSync(join(root, "src/components/preview-frame.tsx"), "utf8");
    assert.doesNotMatch(previewFrame, /allow-same-origin/);
    assert.match(previewFrame, /\binert\b/);
    assert.match(previewFrame, /data-preview-locked/);
    assert.match(previewFrame, /pointerEvents: locked \? "none"/);
    assert.match(previewFrame, /aria-hidden=\{locked/);
    assert.match(previewFrame, /onFocus/);
    const publishedStore = readFileSync(join(root, "src/lib/projects/published-store.ts"), "utf8");
    assert.match(publishedStore, /@netlify\/blobs/);
    assert.match(publishedStore, /validatePublishable/);
    const panel = readFileSync(join(root, "src/components/publish-panel.tsx"), "utf8");
    assert.match(panel, /publishSnapshot/);
    assert.match(panel, /readPublishedId/);
    const overlay = readFileSync(join(root, "src/components/build-overlay.tsx"), "utf8");
    assert.match(overlay, /compact = false/);
    assert.match(overlay, /z-20/);
    assert.doesNotMatch(overlay, /z-12/);
    assert.match(overlay, /Fenix sta creando/);
    assert.match(overlay, /data-fenix-lock/);
    assert.match(overlay, /data-fenix-lock-live/);
    assert.match(overlay, /aria-live="polite"/);
    assert.match(overlay, /bg-\[#07041a\]/);
    assert.doesNotMatch(overlay, /bg-\[#07041a\]\/88/);
    assert.match(overlay, /focusin/);
    assert.match(overlay, /isLockFocusAllowed/);
    assert.match(overlay, /EXIT_LABEL/);
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    const screenPatch = readFileSync(join(root, "workers/visual/screen-patch.mjs"), "utf8");
    assert.doesNotMatch(worker, /card bianche, panel scuro solo se serve un dato, CTA pillola blu/);
    assert.doesNotMatch(worker, /2 colori #1d1d1f \/ #0071e3/);
    assert.match(worker, /function looksDashboard/);
    assert.match(worker, /function looksSite/);
    assert.match(worker, /k === "site" \|\| k === "landing"/);
    assert.match(worker, /body\.kind/);
    assert.match(worker, /function looksPhoneShell/);
    assert.match(screenPatch, /nodo assente/);
    assert.match(worker, /from "\.\/screen-patch\.mjs"/);
    assert.match(worker, /hasScreenTarget\(current, tabId\)/);
    assert.match(worker, /noteAbsent/);
    assert.doesNotMatch(worker, /<template id="t-\$\{tid\}">/);
    assert.match(worker, /DASHBOARD_SYSTEM/);
    assert.match(worker, /SITE_SYSTEM/);
    assert.match(worker, /kind=dashboard/);
    assert.match(worker, /Rifinitura sito \(nav in alto, niente tabbar\)/);
    assert.match(worker, /Layout desktop/);
    assert.match(worker, /function materializeHero/);
    assert.doesNotMatch(worker, /\|\| remote/);
    assert.doesNotMatch(worker, /\|\| hero;/);
    assert.match(worker, /function stripPhoneChromeFromSite/);
    assert.match(worker, /jobsByKey/);
    assert.match(worker, /byKey\.status === "run"/);
    assert.match(worker, /function findReusableJob/);
    assert.match(worker, /activeByProject/);
    assert.match(worker, /idempotency-key/);
    assert.match(worker, /reused: true/);
    assert.match(worker, /function sanitizeIconPack/);
    assert.match(worker, /isAppleChromeSvg/);
    assert.match(worker, /CRAFT_TAB_ICONS/);
    assert.match(worker, /registro a righe/);
    assert.match(worker, /from "\.\/icon-patch\.mjs"/);
    assert.match(worker, /looksLikeIconInstruction\(instruction\)/);
    assert.match(worker, /Patch atomica icona/);
    const iconPatch = readFileSync(join(root, "workers/visual/icon-patch.mjs"), "utf8");
    assert.match(iconPatch, /data-fenix-id/);
    assert.match(iconPatch, /ICON_DELTA_BUDGET/);
    assert.match(iconPatch, /applyIconRevision/);
    assert.match(iconPatch, /refundIconFailure/);
    assert.doesNotMatch(iconPatch, /reasoningEffort/);
    assert.match(iconPatch, /replaceSvgInChunk/);
    assert.match(iconPatch, /return `\$\{svg\}\$\{inner\}`/);
    assert.match(iconPatch, /listTabNodes/);
    assert.match(iconPatch, /namedTabToken/);
    assert.match(iconPatch, /nodeMatchesToken/);
    assert.doesNotMatch(iconPatch, /\\bicon\[ae\] delle tab\\b/);
    const iconPatchTest = readFileSync(join(root, "src/lib/projects/icon-patch.test.ts"), "utf8");
    assert.match(iconPatchTest, /inserts SVG into a target without svg/);
    assert.match(iconPatchTest, /<img src=/);
    assert.match(iconPatchTest, /resolves domain tab ids without data-fenix-id/);
    assert.match(iconPatchTest, /patches a compose-product Agenda/);
    const iconBuildTest = readFileSync(join(root, "src/lib/projects/icon-build.test.ts"), "utf8");
    assert.match(iconBuildTest, /withFetchSpy/);
    assert.match(iconBuildTest, /globalThis\.fetch/);
    assert.match(iconBuildTest, /boot-failure restores snapshot/);
    assert.equal(existsSync(join(root, "src/lib/projects/fixtures/agenda.html")), true);
    assert.equal(existsSync(join(root, "src/lib/projects/fixtures/agenda-clip.html")), true);
    assert.equal(existsSync(join(root, "src/lib/projects/agenda-browser.test.ts")), true);
    assert.equal(existsSync(join(root, "src/lib/projects/icon-build.test.ts")), true);
    assert.equal(existsSync(join(root, "src/lib/projects/icon-build.ts")), true);
  });

  it("drops Apple clone pair from look, shell, types and cards", () => {
    const look = readFileSync(join(root, "src/lib/ai/look.ts"), "utf8");
    assert.doesNotMatch(look, /Stile iOS/);
    assert.doesNotMatch(look, /#f5f5f7 #1d1d1f accento #0071e3/);
    const shell = readFileSync(join(root, "src/lib/ai/app-shell.ts"), "utf8");
    const shellHtml = shell.slice(shell.indexOf("export const APP_SHELL_HTML"));
    assert.match(shell, /coppia #f5f5f7\+#0071e3/);
    assert.doesNotMatch(shellHtml, /#f5f5f7/);
    assert.doesNotMatch(shellHtml, /#0071e3/);
    assert.doesNotMatch(shellHtml, /SF Pro|San Francisco/);
    assert.match(shellHtml, /IBM Plex Sans.*,.*-apple-system/);
    assert.match(shellHtml, /Niente in lista|in lista/);
    assert.doesNotMatch(shellHtml, /class=\\"fk-ledger\\"|class="fk-ledger"/);
    const types = readFileSync(join(root, "src/lib/projects/types.ts"), "utf8");
    assert.doesNotMatch(types, /#f5f5f7/);
    assert.doesNotMatch(types, /#0071e3/);
    const card = readFileSync(join(root, "src/components/project-card.tsx"), "utf8");
    assert.doesNotMatch(card, /#f5f5f7/);
    const scheme = readFileSync(join(root, "src/lib/projects/color-scheme.ts"), "utf8");
    assert.doesNotMatch(scheme, /#f5f5f7/);
    assert.doesNotMatch(scheme, /#0071e3/);
    assert.match(scheme, /data-fenix-ready/);
    assert.match(scheme, /ready:\s*function/);
    assert.match(scheme, /data-fenix-desk/);
    assert.match(scheme, /max-width:1120px/);
    assert.doesNotMatch(scheme, /max-width:40rem/);
    assert.match(scheme, /nav\.bottom-tab,nav\.fk-tab\{display:none!important\}/);
    assert.match(scheme, /min-height:44px/);
    assert.match(scheme, /:focus-visible/);
    assert.match(scheme, /\.fk-btn\{[^}]*border-radius:12px/);
    assert.doesNotMatch(scheme, /max-width:32vw/);
    assert.doesNotMatch(scheme, /\.logo,\.brand[^}]*text-overflow:ellipsis/);
    assert.doesNotMatch(scheme, /nav[^}]*flex-wrap:nowrap!important/);
    assert.match(scheme, /fenix-boot-error/);
    assert.match(scheme, /fenix-boot-ok/);
    assert.match(scheme, /ev\.target !== window/);
    assert.match(scheme, /data-fenix-img/);
    assert.match(scheme, /unhandledrejection/);
    assert.match(scheme, /data-fenix-boot-error/);
    assert.match(scheme, /data-fenix-boot-ok/);
    assert.doesNotMatch(scheme, /sandboxNoise/);
    assert.match(scheme, /memoryStorage/);
    assert.doesNotMatch(scheme, /void window\.localStorage/);
    assert.doesNotMatch(scheme, /defineProperty\(window, "localStorage"/);
    assert.match(scheme, /absolutizeCraftHero/);
    assert.match(look, /waitPreviewBoot/);
    assert.match(look, /rememberBootError/);
    assert.match(look, /rememberBootOk/);
    assert.match(look, /Avvio senza segnale/);
    assert.match(look, /fenix-boot-ok/);
    const crud = readFileSync(join(root, "src/lib/projects/dashboard-crud.ts"), "utf8");
    assert.match(crud, /data-fenix-crud/);
    assert.match(crud, /1f5f8b/);
    const runBuild = readFileSync(join(root, "src/lib/ai/run-build.ts"), "utf8");
    assert.doesNotMatch(runBuild, /Fenix 2: Vite \+ React/);
    assert.match(runBuild, /BOOT_REPAIR_MAX = 2/);
    assert.match(runBuild, /repairBootFailures/);
    assert.match(runBuild, /waitPreviewBoot/);
    assert.match(runBuild, /getPreviewBootOk/);
    assert.match(runBuild, /polishedOnce/);
    assert.match(runBuild, /Anteprima già rifinita/);
    assert.match(runBuild, /STALE_JOB/);
    assert.match(runBuild, /captureStableSnapshot/);
    assert.match(runBuild, /stillCurrent/);
    assert.match(runBuild, /restoreStablePatch/);
    assert.match(runBuild, /lastStableHtml/);
    assert.match(runBuild, /withoutPronto/);
    assert.match(runBuild, /SITE_POLISH_INSTRUCTION/);
    assert.match(runBuild, /if \(!\(instruction \|\| isIOS\(\)\) && phone\)/);
    assert.match(runBuild, /looksLikeIconInstruction/);
    assert.match(runBuild, /applyIconRevision/);
    assert.match(runBuild, /runIconBuild/);
    assert.match(runBuild, /runIconRevisionFlow/);
    assert.match(runBuild, /Nessuna seconda POST/);
    const runFn = runBuild.slice(runBuild.indexOf("export async function runBuild"));
    assert.ok(
      runFn.indexOf("looksLikeIconInstruction") < runFn.indexOf("spendCredit"),
      "icon gate must run before spendCredit",
    );
    const polishFn = runBuild.slice(runBuild.indexOf("async function polishDraft"));
    assert.ok(
      polishFn.indexOf("looksLikeIconInstruction") < polishFn.indexOf("startPolishJob"),
      "icon polish must not POST the visual worker",
    );
    const compose = readFileSync(join(root, "src/lib/ai/compose-product.ts"), "utf8");
    assert.match(compose, /data-fenix-id="icon:\$\{tab\.id\}"/);
    assert.match(compose, /data-fenix-id="icon:'\+t\.id\+'/);
    assert.match(compose, /data-fenix-rail="day"/);
    assert.match(compose, /agendaRailMarkup/);
    assert.match(compose, /--t-headline/);
    assert.match(compose, /grammar\.id === "agenda"/);
    assert.doesNotMatch(compose, /state-empty:before/);
    assert.match(compose, /function weekDays/);
    assert.match(compose, /AGENDA_CYCLE/);
    assert.match(compose, /selectedDay/);
    assert.match(compose, /name="ora"/);
    assert.match(compose, /name="luogo"/);
    assert.match(compose, /name="cliente"/);
    assert.match(compose, /name="data"/);
    assert.match(compose, /function nowDate/);
    assert.match(compose, /checkValidity/);
    assert.match(compose, /reportValidity/);
    assert.match(compose, /\["Lun","Mar","Mer","Gio","Ven","Sab","Dom"\]/);
    assert.doesNotMatch(compose, /Math\.min\(days\.length-1,todayIdx/);
    assert.doesNotMatch(compose, /if\(!rows\.length\) return html\+emptyBox/);
    assert.doesNotMatch(compose, /idx%5/);    assert.doesNotMatch(compose, /\.slot\{[^}]*padding:18px 0/);
    assert.match(compose, /padding:18px 20px/);
    assert.match(compose, /closest\("\.week-day\[data-day\]"\)/);
    assert.match(compose, /function mondayOf/);
    assert.match(compose, /data-act="week-prev"/);
    assert.match(compose, /data-act="week-today"/);
    assert.match(compose, /id="day-label"/);
    assert.match(compose, /function persistThen/);
    assert.match(compose, /data-fenix-persist/);
    assert.match(compose, /data-fenix-queue/);
    assert.match(compose, /function payloadForHead/);
    assert.match(compose, /function enqueueOp/);
    assert.match(compose, /function renderKeepForm/);
    assert.match(compose, /function finishBoot/);
    assert.match(compose, /op\.patch/);
    assert.match(compose, /AGENDA_CYCLE\[item\.status\]\|\|"confermato"/);
    assert.match(compose, /renderKeepForm\(\);\s*return persistThen/);
    assert.match(compose, /return window\.Fenix\.save\(COL, payload\)/);
    assert.match(compose, /fromLoad && !pendingOps\.length/);
    assert.doesNotMatch(compose, /if\(cur\.status===nextStatus\) cur\.status=prevStatus/);
    assert.doesNotMatch(compose, /data=snapAdv/);
    assert.doesNotMatch(compose, /if\(persistBusy\) return;/);
    assert.doesNotMatch(compose, /if\(persistBusy\) return false/);
    assert.doesNotMatch(compose, /status:\(prev&&prev.status\)/);
    assert.doesNotMatch(compose, /pendingOps=\[\];\s*confirmed/);
    assert.doesNotMatch(compose, /function finishBoot[\s\S]{0,500}pendingOps=\[\];/);
    assert.doesNotMatch(compose, /home universale grigia/);
    assert.doesNotMatch(compose, /due riquadri vuoti/);
    assert.doesNotMatch(compose, /"label":"Scarto"/);
    assert.match(compose, /if\(gen!==flashGen\) return;/);
    assert.match(compose, /setTimeout\(function\(\)\{/);
    const agendaRuntime = readFileSync(join(root, "src/lib/projects/agenda-runtime-browser.test.ts"), "utf8");
    assert.match(agendaRuntime, /waitFor\(\{ state: "hidden", timeout: 4000 \}\)/);
    assert.match(agendaRuntime, /setTimeout\(ack, 600\)/);
    assert.match(agendaRuntime, /\[data-status="confermato"\]/);
    assert.match(agendaRuntime, /data-fenix-persist='busy'/);
    assert.match(agendaRuntime, /Alpha coda/);
    assert.match(agendaRuntime, /__rejectsLeft/);
    assert.match(agendaRuntime, /__rejectPlan/);
    assert.match(agendaRuntime, /__hold/);
    assert.match(agendaRuntime, /Gamma coda/);
    assert.match(agendaRuntime, /Stessa riga/);
    assert.match(agendaRuntime, /Delta patch/);
    assert.match(agendaRuntime, /Bozza viva/);
    assert.match(agendaRuntime, /__loadDelay/);
    assert.match(agendaRuntime, /Agenda persist late boot/);
    const fiveBrief = readFileSync(join(root, "src/lib/ai/compose-product-browser.test.ts"), "utf8");
    assert.match(fiveBrief, /async function clickActOnHeading/);
    assert.match(fiveBrief, /locator\(`\[data-act="\$\{act\}"\]`\)\s*\n\s*\.click\(\)/);
    assert.doesNotMatch(fiveBrief, /btn\.click\(\)/);
    assert.match(fiveBrief, /width: 320/);
    assert.match(fiveBrief, /getBoundingClientRect/);
    assert.match(fiveBrief, /parent bffc58f/);
    const recorded = readFileSync(join(root, "src/lib/ai/repair.recorded.test.ts"), "utf8");
    assert.match(recorded, /POLISH_REPAIR_LIVE_VERIFIED = false/);
    assert.match(recorded, /from "\.\/parse\.ts"/);
    assert.match(recorded, /parseBuildOutput/);
    assert.match(recorded, /gateBuildResult/);
    assert.match(recorded, /repairBuild/);
    assert.match(recorded, /CONTRACT_REPAIR_MAX/);
    assert.match(recorded, /prepareSrcDoc/);
    assert.doesNotMatch(recorded, /stubFromRecorded/);
    assert.doesNotMatch(recorded, /XAI_CHAT_COMPLETIONS_URL/);
    assert.doesNotMatch(compose, /void window\.Fenix\.save/);
    assert.match(compose, /GRAPHIC_FIVE_PARENT_SHA/);
    assert.match(compose, /bffc58f1af1ee22e69b99a0ed3dd65eaba8822f9/);
    assert.match(compose, /backdrop-filter:saturate\(1\.8\) blur\(20px\)/);
    assert.match(compose, /ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI"/);
    assert.match(compose, /function artOf\(/);
    assert.doesNotMatch(compose, /content:" · in prova"/);
    assert.match(compose, /aria-label="Modifica"/);
    assert.match(compose, /const AGENDA_EDIT_GLYPH=/);
    const imagery = readFileSync(join(root, "src/lib/ai/domain-imagery.ts"), "utf8");
    assert.match(imagery, /slot === 0 \? "meet" : "slice"/);
    assert.match(imagery, /data-fit="\$\{resolved\}"/);
    assert.match(imagery, /function perfumeThumbViewBox/);
    assert.match(imagery, /data-focus=/);
    assert.match(imagery, /PERFUME_SUBJECT/);
    assert.match(compose, /class="collection"/);
    assert.match(compose, /align-items:start/);
    assert.match(compose, /nav\.tabs svg\{[^}]*overflow:visible/);
    assert.match(compose, />Avanti</);
    assert.doesNotMatch(compose, /Avanza slot/);
    assert.match(compose, /flex-wrap:nowrap/);
    assert.match(compose, /data-family=/);
    assert.match(compose, /family-chrome /);
    assert.match(compose, /html\[data-family\]::before/);
    assert.match(compose, /function displayStack/);
    assert.match(compose, /function isOperationalApp/);
    assert.match(compose, /ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI"/);
    assert.equal(existsSync(join(root, "src/lib/projects/agenda-runtime-browser.test.ts")), true);
    const runtime = readFileSync(join(root, "src/lib/projects/color-scheme.ts"), "utf8");
    assert.match(runtime, /function productOwnsList/);
    assert.match(runtime, /if \(productOwnsList\(\)\) return;/);
    assert.match(runtime, /data-fenix-rail/);
    assert.match(runtime, /timeout: true/);
    assert.match(runtime, /res\.ok === false/);
    assert.match(runtime, /export function paletteHueConflict/);
    assert.doesNotMatch(runtime, /bg = "#111827"/);
    assert.doesNotMatch(runtime, /accent = "#2dd4bf"/);
    assert.doesNotMatch(runtime, /muddyWarmDark/);
    const craft = readFileSync(join(root, "src/lib/projects/craft-icons.ts"), "utf8");
    assert.match(craft, /data-fenix-id="icon:\$\{t\.id\}"/);
    assert.match(craft, /data-icon-grid="24"/);
    assert.match(craft, /FIRST_RUN_HOME/);
    assert.doesNotMatch(craft, /LEDGER_HOME/);
    assert.match(craft, /pot: navIcon/);
    assert.match(craft, /M7\.2 7\.4h9\.6/);
    assert.match(craft, /M7\.2 10\.2H4\.6/);
    assert.doesNotMatch(craft, /M6\.6 10\.4h10\.8/);
    const appShell = readFileSync(join(root, "src/lib/ai/app-shell.ts"), "utf8");
    assert.match(appShell, /data-fenix-id="icon:app"/);
    const iconFn = runBuild.slice(runBuild.indexOf("async function runIconBuild"));
    assert.match(iconFn, /runIconRevisionFlow/);
    assert.match(iconFn, /settlePreviewBoot/);
    assert.doesNotMatch(iconFn, /repairBootFailures/);
    assert.doesNotMatch(iconFn, /consumeStream/);
    const iconFlow = readFileSync(join(root, "src/lib/projects/icon-build.ts"), "utf8");
    assert.match(iconFlow, /settleBoot/);
    assert.doesNotMatch(iconFlow, /repairBootFailures/);
    assert.doesNotMatch(iconFlow, /consumeStream/);
    assert.doesNotMatch(iconFlow, /\/api\/build/);
    assert.doesNotMatch(iconFlow, /\bfetch\s*\(/);
    assert.doesNotMatch(iconFlow, /startPolishJob/);
    assert.match(runBuild, /isIOS\(\) \|\| desk/);
    assert.match(runBuild, /GENERATE_POLL_MAX = 300/);
    assert.match(runBuild, /isTransientNetwork/);
    assert.match(runBuild, /throw new Error\(event\.error \|\| "network error"\)/);
    assert.match(runBuild, /proxyAnswered/);
    assert.match(runBuild, /else if \(isIOS\(\) \|\| desk\)/);
    assert.doesNotMatch(runBuild, /alreadyPronto/);
    const buildApi = readFileSync(join(root, "src/routes/api/build.ts"), "utf8");
    assert.match(buildApi, /materializeHero/);
    assert.match(buildApi, /SITE_PROMPT/);
    assert.match(buildApi, /const desk = lockKind === "site"/);
    const prompts = readFileSync(join(root, "src/lib/ai/prompts.shared.ts"), "utf8");
    assert.match(prompts, /export const SITE_PROMPT/);
    assert.match(prompts, /kind":"site"/);
    const qa = readFileSync(join(root, "src/lib/ai/qa.ts"), "utf8");
    assert.match(qa, /isDeskKind\(kind\)\) return null/);
    const suggest = readFileSync(join(root, "src/lib/ai/suggest.ts"), "utf8");
    assert.match(suggest, /Nav in alto: Home, Bottega, Lavori, Visita/);
    assert.match(suggest, /Le cinque tab devono aprire/);
    const hero = readFileSync(join(root, "src/lib/ai/hero-image.ts"), "utf8");
    assert.match(hero, /export async function materializeHero/);
    assert.match(hero, /data:image/);
    assert.match(hero, /this.removeAttribute\('src'\)/);
    assert.match(hero, /fk-tab\|bottom-tab/);
    assert.match(hero, /min\(52vh,560px\)/);
    assert.match(hero, /fk-hero-craft/);
    assert.match(hero, /scrubCraftMedia/);
    assert.match(hero, /injectCraftHero/);
    assert.match(hero, /\/craft-hero\.jpg/);
    assert.match(hero, /CRAFT_HERO_SRC = "\/craft-hero\.jpg"/);
    assert.equal(existsSync(join(root, "public/craft-hero.jpg")), true);
    for (const file of ["craft-shelf.jpg", "craft-vase.jpg", "craft-bowl.jpg", "craft-plate.jpg", "craft-pitcher.jpg"]) {
      assert.equal(existsSync(join(root, "public", file)), true, file);
    }
    const storeSrc = readFileSync(join(root, "src/lib/projects/published-store.ts"), "utf8");
    assert.match(storeSrc, /Sito pubblico senza titolare: immutabile/);
    const publishClient = readFileSync(join(root, "src/lib/projects/publish-client.ts"), "utf8");
    assert.match(publishClient, /isLegacyImmutableError/);
    assert.match(publishClient, /randomUUID/);
    assert.match(publishClient, /rememberPublishedId/);
    assert.match(publishClient, /readPublishedId/);
    assert.match(publishClient, /resolvePublishedId/);
    assert.match(publishClient, /PUBLISHED_MAP_KEY/);
    const sitoSrc = readFileSync(join(root, "src/routes/sito.$projectId.tsx"), "utf8");
    assert.match(sitoSrc, /absolute inset-0/);
    const edge = readFileSync(join(root, "netlify/edge-functions/build.ts"), "utf8");
    assert.match(edge, /SITE_PROMPT/);
    assert.match(edge, /const desk = lockKind === "site"/);
    assert.doesNotMatch(runBuild, /Pronto\. \$\{result\.name\} è in anteprima/);
    const resume = runBuild.slice(
      runBuild.indexOf("export async function resumePolish"),
      runBuild.indexOf("export async function runBuild"),
    );
    assert.match(resume, /repairBootFailures/);
    assert.match(resume, /SITE_POLISH_INSTRUCTION/);
    assert.doesNotMatch(runBuild, /JOB_STILL_RUNNING \|\| \/Riprendi rifinitura/);
    assert.match(runBuild, /if \(workerError === JOB_STILL_RUNNING\)/);
    const fenixBrowser = readFileSync(join(root, "src/lib/projects/fenix-browser.test.ts"), "utf8");
    const studioKit = readFileSync(join(root, "src/lib/projects/studio-kit-browser.test.ts"), "utf8");
    assert.doesNotMatch(fenixBrowser, /new Promise\(\(\) => \{/);
    assert.doesNotMatch(studioKit, /new Promise\(\(\) => \{/);
    assert.match(fenixBrowser, /holdVisualWork/);
    assert.match(fenixBrowser, /isolatedPage/);
    assert.match(studioKit, /holdVisualWork/);
    assert.match(studioKit, /STALE-WIN/);
    assert.match(studioKit, /data-fenix-lock-live/);
    assert.match(studioKit, /reattach must not POST/);
    const harness = readFileSync(join(root, "src/lib/projects/playwright-harness.ts"), "utf8");
    assert.match(harness, /instrumentBrowser/);
    assert.match(harness, /browser\.newContext/);
    assert.match(harness, /fonts\.googleapis\.com/);
    assert.match(harness, /LAUNCH_TIMEOUT_MS = 30_000/);
    assert.match(harness, /timeout:\s*LAUNCH_TIMEOUT_MS/);
    assert.match(harness, /CLOSE_TIMEOUT_MS = 5_000/);
    assert.match(harness, /isTransientLaunchError/);
    assert.match(harness, /launchChromiumWith/);
    assert.match(harness, /withChromiumLease/);
    assert.match(harness, /sweepOwnedLaunch/);
    assert.match(harness, /resolveInsideRoot/);
    assert.match(harness, /dirname\(/);
    assert.match(harness, /basename\(/);
    assert.match(harness, /RETRY_BACKOFF_MS/);
    assert.match(harness, /pidOwningDir/);
    assert.match(harness, /chromium\.launch\(/);
    assert.doesNotMatch(harness, /sweepStaleChromium/);
    assert.doesNotMatch(harness, /isPlaywrightChromiumProcess/);
    assert.doesNotMatch(harness, /launchServer/);
    assert.doesNotMatch(harness, /chromium\.connect\(/);
    assert.doesNotMatch(harness, /playwright_chromiumdev_profile-/);
    const harnessTest = readFileSync(join(root, "src/lib/projects/playwright-harness.test.ts"), "utf8");
    assert.match(harnessTest, /canonicalizes Darwin-style tmp aliases/);
    const testFiles = readdirSync(join(root, "src"), { recursive: true, encoding: "utf8" }) as string[];
    for (const rel of testFiles) {
      if (!rel.endsWith(".test.ts")) continue;
      if (rel.endsWith("playwright-harness.test.ts")) continue;
      const src = readFileSync(join(root, "src", rel), "utf8");
      if (!src.includes("playwright")) continue;
      assert.doesNotMatch(src, /chromium\.launch\(/, rel);
      if (
        /launchChromium|browser\.newPage|isolatedPage/.test(src) ||
        /browser\.test\.ts$/.test(rel.replaceAll("\\", "/"))
      ) {
        assert.match(src, /launchChromium/, rel);
      }
    }
    const releaseClient = readFileSync(join(root, "src/lib/release/client.ts"), "utf8");
    const releasePanel = readFileSync(join(root, "src/components/publish-panel.tsx"), "utf8");
    const releaseSecrets = readFileSync(join(root, "src/lib/release/secrets.server.ts"), "utf8");
    const releaseHttp = readFileSync(join(root, "src/lib/release/http.ts"), "utf8");
    const releaseEngine = readFileSync(join(root, "src/lib/release/engine.ts"), "utf8");
    const releaseFn = readFileSync(join(root, "netlify/functions/release.ts"), "utf8");
    assert.match(releasePanel, /startRelease/);
    assert.match(releasePanel, /loadReleaseJob/);
    assert.match(releasePanel, /job\.status !== "run"/);
    assert.match(releasePanel, /App Store Connect/);
    assert.match(releasePanel, /TestFlight/);
    assert.doesNotMatch(releasePanel, /secrets\.server/);
    assert.doesNotMatch(releasePanel, /APPLE_PRIVATE_KEY/);
    assert.doesNotMatch(releasePanel, /BEGIN PRIVATE KEY/);
    assert.doesNotMatch(releaseClient, /process\.env/);
    assert.doesNotMatch(releaseClient, /secrets\.server/);
    assert.match(releaseSecrets, /APPLE_PRIVATE_KEY/);
    assert.match(releaseSecrets, /GOOGLE_PLAY_SERVICE_ACCOUNT/);
    assert.match(releaseSecrets, /APPLE_TEAM_ID/);
    assert.match(releaseSecrets, /ANDROID_KEYSTORE_PATH/);
    assert.match(releaseSecrets, /ANDROID_KEYSTORE_BASE64/);
    assert.match(releaseSecrets, /ANDROID_KEY_ALIAS/);
    assert.match(releaseHttp, /handleReleaseCollection/);
    assert.match(releaseEngine, /gateHtml/);
    assert.match(releaseEngine, /claimReleaseKey/);
    assert.match(releaseEngine, /withLease/);
    assert.match(releaseEngine, /result\.reconciled/);
    assert.match(releaseEngine, /jobIdFromKey/);
    assert.match(releaseEngine, /createsInflight/);
    assert.match(releaseEngine, /asHexKey/);
    assert.match(releaseFn, /path: "\/api\/release"/);
    const storeApi = readFileSync(join(root, "src/lib/release/store-api.ts"), "utf8");
    assert.match(storeApi, /applePreflight/);
    assert.match(storeApi, /googlePreflight/);
    assert.doesNotMatch(releaseClient, /store-api/);
    assert.doesNotMatch(releasePanel, /store-api/);
    const storeSrcRel = readFileSync(join(root, "src/lib/release/store.ts"), "utf8");
    assert.match(storeSrcRel, /claimReleaseKey/);
    assert.match(storeSrcRel, /flag: "wx"/);
    assert.match(storeSrcRel, /ON CONFLICT \(idempotency_key\)/);
    assert.match(storeSrcRel, /createReleaseStore/);
    const migrationRel = readFileSync(join(root, "migrations/0002_release_jobs.sql"), "utf8");
    assert.match(migrationRel, /create table if not exists release_jobs/);
    assert.match(migrationRel, /idempotency_key text not null unique/);
    const iosSrc = readFileSync(join(root, "src/lib/release/ios.ts"), "utf8");
    assert.match(iosSrc, /xcodebuild/);
    assert.match(iosSrc, /altool/);
    assert.match(iosSrc, /appleListLatestBuild/);
    assert.match(iosSrc, /withAppleApiKey/);
    assert.match(iosSrc, /allowProvisioningUpdates|authenticationKeyPath|withIosCodeSign/);
    const appleKeySrc = readFileSync(join(root, "src/lib/release/apple-key.ts"), "utf8");
    assert.match(appleKeySrc, /API_PRIVATE_KEYS_DIR/);
    assert.match(appleKeySrc, /AuthKey_/);
    assert.match(appleKeySrc, /withIosCodeSign/);
    const nativeSrc = readFileSync(join(root, "src/lib/release/native.ts"), "utf8");
    assert.match(nativeSrc, /isa = PBXNativeTarget/);
    assert.match(nativeSrc, /xmlns:android/);
    assert.doesNotMatch(nativeSrc, /\/\/ Generated Fenix iOS wrapper/);
    const androidSrc = readFileSync(join(root, "src/lib/release/android.ts"), "utf8");
    assert.match(androidSrc, /bundleRelease/);
    assert.match(androidSrc, /jarsigner/);
    assert.match(androidSrc, /-keystore/);
    assert.match(androidSrc, /keystoreBase64|withAndroidKeystore/);
    assert.match(androidSrc, /playInsertEdit/);
    assert.match(androidSrc, /playUploadBundle/);
    assert.match(androidSrc, /playCommitInternal/);
    assert.match(androidSrc, /inflight === "play-commit"/);
    const webSrc = readFileSync(join(root, "src/lib/release/web.ts"), "utf8");
    assert.match(webSrc, /netlifyFindOrCreateSite/);
    assert.match(webSrc, /netlifyListDeploys/);
    assert.match(webSrc, /netlifyCreateDeploy/);
    assert.match(webSrc, /netlifyGetDeploy/);
    assert.match(webSrc, /liveUrl|ssl_url/);
    const dispatchSrc = readFileSync(join(root, "src/lib/release/dispatch.ts"), "utf8");
    assert.match(dispatchSrc, /shouldDispatchNative/);
    assert.match(dispatchSrc, /workflow_dispatch|release-ios.yml/);
    assert.match(dispatchSrc, /workflowRunId/);
    assert.match(dispatchSrc, /step: "pipeline"/);
    const deployApi = readFileSync(join(root, "src/lib/release/deploy-api.ts"), "utf8");
    assert.match(deployApi, /edits\/.+\/tracks\/internal|\/edits\/" \+|encodeURIComponent\(edit.id\)/);
    assert.doesNotMatch(
      deployApi.slice(deployApi.indexOf("export async function playGetInternalTrack")),
      /applications\/" \+\s*encodeURIComponent\(packageName\) \+\s*"\/tracks\/internal"/,
    );
    const runnerSrc = readFileSync(join(root, "src/lib/release/runner.ts"), "utf8");
    assert.match(runnerSrc, /fixtureCommand/);
    assert.match(runnerSrc, /xcodebuild/);
    const netlifyToml = readFileSync(join(root, "netlify.toml"), "utf8");
    assert.match(netlifyToml, /sync-static-publish\.mjs/);
    assert.match(netlifyToml, /publish = "\.output\/public"/);
    assert.doesNotMatch(netlifyToml, /publish = "dist"/);
    const pkgJson = readFileSync(join(root, "package.json"), "utf8");
    assert.match(pkgJson, /sync-static-publish\.mjs/);
    const envExample = readFileSync(join(root, ".env.example"), "utf8");
    assert.match(envExample, /APPLE_ISSUER_ID=/);
    assert.match(envExample, /APPLE_TEAM_ID=/);
    assert.match(envExample, /ANDROID_KEYSTORE_PATH=/);
    assert.match(envExample, /ANDROID_KEYSTORE_BASE64=/);
    assert.match(envExample, /ANDROID_KEY_ALIAS=/);
    assert.match(envExample, /FENIX_RELEASE_CALLBACK_SECRET=/);
    assert.doesNotMatch(envExample, /BEGIN PRIVATE KEY/);
    const clientRoots = [join(root, "dist/assets"), join(root, ".output/public/assets")];
    for (const dir of clientRoots) {
      if (!existsSync(dir)) continue;
      for (const name of readdirSync(dir)) {
        if (!/\.(js|mjs|css|html)$/.test(name)) continue;
        const text = readFileSync(join(dir, name), "utf8");
        assert.doesNotMatch(text, /APPLE_PRIVATE_KEY/, name);
        assert.doesNotMatch(text, /BEGIN PRIVATE KEY/, name);
        assert.doesNotMatch(text, /GOOGLE_PLAY_SERVICE_ACCOUNT/, name);
        assert.doesNotMatch(text, /secrets\.server/, name);
      }
    }
    const modelSrc = readFileSync(join(root, "src/lib/ai/model.ts"), "utf8");
    assert.match(modelSrc, /FENIX_MODEL = "grok-build-0.1"/);
    assert.doesNotMatch(modelSrc, /reasoningEffort/);
  });

  it("suggests nav in alto for a site, not five phone tabs", async () => {
    const { suggestEdits } = await import("../../lib/ai/suggest.ts");
    const tips = suggestEdits("FORMATO: sito web. kind=site. Bottega Terra", "Bottega Terra");
    assert.equal(tips.some((t) => /cinque tab/i.test(t)), false);
    assert.equal(tips.some((t) => /nav in alto/i.test(t)), true);
    const appTips = suggestEdits("FORMATO: app telefono. kind=app. Taccuino");
    assert.equal(appTips.some((t) => /cinque tab/i.test(t)), true);
  });

  it("rescues leaked phone-kit CSS and refuses to publish the dump", () => {
    const scheme = readFileSync(join(root, "src/lib/projects/color-scheme.ts"), "utf8");
    assert.match(scheme, /export function looksLikeLeakedCss/);
    assert.match(scheme, /export function repairLeakedCss/);
    assert.match(scheme, /export function looksLikeCssDump/);
    assert.match(scheme, /data-fenix-rescued/);
    assert.match(scheme, /next = repairLeakedCss\(next\)/);
    assert.match(scheme, /\\u0026lt;\\\/\?style/);
    const validate = readFileSync(join(root, "src/lib/projects/validate-html.ts"), "utf8");
    assert.match(validate, /CSS tecnico visibile/);
    assert.match(validate, /looksLikeLeakedCss/);
    const recover = readFileSync(join(root, "src/lib/projects/recover.ts"), "utf8");
    assert.match(recover, /repairLeakedCss/);
    const store = readFileSync(join(root, "src/lib/projects/store.ts"), "utf8");
    assert.match(store, /repairLeakedCss/);
    const files = readFileSync(join(root, "src/lib/projects/files.ts"), "utf8");
    assert.match(files, /!looksLikeLeakedCss\(main\)/);
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    const screenPatch = readFileSync(join(root, "workers/visual/screen-patch.mjs"), "utf8");
    assert.match(screenPatch, /export function looksLikeCssDump/);
    assert.match(screenPatch, /if \(looksLikeCssDump\(inner\)\)/);
    assert.match(worker, /if \(looksLikeCssDump\(m\[1\]\)\) return html/);
    assert.equal(existsSync(join(root, "src/lib/projects/fixtures/leaked-phone-css.html")), true);
    const leaked = readFileSync(join(root, "src/lib/projects/fixtures/leaked-phone-css.html"), "utf8");
    assert.match(leaked, /\.fk-hello\{/);
    assert.match(leaked, /\.fk-tab,/);
    assert.match(leaked, /\.fk-sheet\{/);
    assert.match(leaked, /<main class="fk-main"/);
  });

  it("github export is server-only GitHub App, ZIP stays, no parity claim", () => {
    const client = readFileSync(join(root, "src/lib/github/client.ts"), "utf8");
    const panel = readFileSync(join(root, "src/components/export-panel.tsx"), "utf8");
    const studio = readFileSync(join(root, "src/routes/studio.$projectId.tsx"), "utf8");
    const api = readFileSync(join(root, "src/lib/github/api.ts"), "utf8");
    const types = readFileSync(join(root, "src/lib/github/types.ts"), "utf8");
    const jwt = readFileSync(join(root, "src/lib/github/jwt.ts"), "utf8");
    const secrets = readFileSync(join(root, "src/lib/github/secrets.server.ts"), "utf8");
    const http = readFileSync(join(root, "src/lib/github/http.ts"), "utf8");
    const refs = readFileSync(join(root, "src/lib/github/references.md"), "utf8");
    const envExample = readFileSync(join(root, ".env.example"), "utf8");
    const fn = readFileSync(join(root, "netlify/functions/github.ts"), "utf8");
    const fnExport = readFileSync(join(root, "netlify/functions/github-export.ts"), "utf8");
    const gap = readFileSync(join(root, "src/lib/projects/fase3-gap.ts"), "utf8");
    const state = readFileSync(join(root, "src/lib/github/state.ts"), "utf8");
    const store = readFileSync(join(root, "src/lib/github/store.ts"), "utf8");
    const migration = readFileSync(join(root, "migrations/0003_github_connect_nonces.sql"), "utf8");
    assert.doesNotMatch(client, /secrets\.server/);
    assert.doesNotMatch(client, /GITHUB_APP_PRIVATE_KEY/);
    assert.doesNotMatch(client, /process\.env/);
    assert.doesNotMatch(client, /fenix_gh/);
    assert.match(client, /credentials: "same-origin"/);
    assert.doesNotMatch(panel, /secrets\.server/);
    assert.doesNotMatch(panel, /GITHUB_APP_PRIVATE_KEY/);
    assert.doesNotMatch(panel, /fenix_gh/);
    assert.match(panel, /GitHub non configurato/);
    assert.match(panel, /Scarica \.zip/);
    assert.match(panel, /Connetti GitHub/);
    assert.match(studio, /ExportPanel/);
    assert.match(studio, /aria-label="Esporta"/);
    assert.match(api, /force: false/);
    assert.match(api, /GITHUB_API_VERSION/);
    assert.match(types, /2026-03-10/);
    assert.match(jwt, /RS256/);
    assert.match(jwt, /now - 60/);
    assert.match(secrets, /GITHUB_APP_PRIVATE_KEY/);
    assert.match(http, /GitHub non configurato/);
    assert.match(http, /database durevole/);
    assert.match(http, /githubNonceStoreReady/);
    assert.match(http, /cookieMatchesState/);
    assert.match(http, /clearConnectCookieHeader/);
    assert.match(state, /HttpOnly/);
    assert.match(state, /SameSite=Lax/);
    assert.match(state, /CONNECT_COOKIE_PATH = "\/api\/github\/callback"/);
    assert.match(state, /Path=\$\{CONNECT_COOKIE_PATH\}/);
    assert.match(state, /fenix_gh/);
    assert.match(state, /purpose: "state" \| "cookie"/);
    assert.match(state, /fenix-github-\$\{purpose\}/);
    assert.match(store, /ON CONFLICT \(nonce\)/);
    assert.match(store, /github_connect_nonces/);
    assert.match(store, /githubNonceStoreReady/);
    assert.doesNotMatch(store, /blobKey\("nonce"/);
    assert.match(migration, /github_connect_nonces/);
    assert.match(fn, /path: "\/api\/github"/);
    assert.match(fnExport, /path: "\/api\/github\/export"/);
    assert.match(envExample, /GITHUB_APP_ID=/);
    assert.match(envExample, /GITHUB_APP_SLUG=/);
    assert.match(envExample, /0003_github_connect_nonces/);
    assert.match(envExample, /DATABASE_URL/);
    assert.doesNotMatch(envExample, /VITE_GITHUB/);
    assert.match(refs, /2026-03-10/);
    assert.match(refs, /force/);
    assert.match(refs, /HttpOnly/);
    assert.match(refs, /github_connect_nonces/);
    assert.match(refs, /DATABASE_URL/);
    assert.match(gap, /github-export/);
    assert.match(gap, /GitHub App server-only/);
    assert.match(gap, /cookie HttpOnly CSRF/);
    assert.match(gap, /DATABASE_URL/);
    assert.doesNotMatch(gap, /feature-complete|uguale a Emergent/);
    const clientRoots = [join(root, "dist/assets"), join(root, ".output/public/assets")];
    for (const dir of clientRoots) {
      if (!existsSync(dir)) continue;
      for (const name of readdirSync(dir)) {
        if (!/\.(js|mjs|css|html)$/.test(name)) continue;
        const text = readFileSync(join(dir, name), "utf8");
        assert.doesNotMatch(text, /GITHUB_APP_PRIVATE_KEY/, name);
        assert.doesNotMatch(text, /VITE_GITHUB/, name);
      }
    }
  });

  it("quality protocol is shared, grok-build-0.1 only, planner is static", () => {
    const plan = readFileSync(join(root, "src/lib/ai/plan.ts"), "utf8");
    assert.doesNotMatch(plan, /fetch\(/);
    assert.doesNotMatch(plan, /XAI_CHAT_COMPLETIONS_URL/);
    assert.match(plan, /planContract/);
    const contract = readFileSync(join(root, "src/lib/ai/build-contract.ts"), "utf8");
    assert.match(contract, /BUILD_ROLES/);
    assert.match(contract, /criticBudget/);
    assert.match(contract, /evaluateContract/);
    assert.doesNotMatch(contract, /reasoning_effort|reasoningEffort/);
    const prompts = readFileSync(join(root, "src/lib/ai/prompts.shared.ts"), "utf8");
    assert.match(prompts, /export const PLAN_PROMPT/);
    assert.match(prompts, /export const REPAIR_PROMPT/);
    const repair = readFileSync(join(root, "src/lib/ai/repair.ts"), "utf8");
    assert.match(repair, /from "\.\/prompts\.shared(?:\.ts)?"/);
    const api = readFileSync(join(root, "src/routes/api/build.ts"), "utf8");
    assert.match(api, /planContract/);
    assert.match(api, /contractInstruction/);
    assert.match(api, /criticBudget/);
    assert.match(api, /gateBuildResult/);
    const adapter = readFileSync(join(root, "src/lib/projects/fenix-adapter.ts"), "utf8");
    assert.match(adapter, /evaluateContract/);
    assert.match(adapter, /formatContractErrors/);
    assert.match(adapter, /CONTRACT_REPAIR_MAX/);
    const edge = readFileSync(join(root, "netlify/edge-functions/build.ts"), "utf8");
    assert.match(edge, /planContract/);
    assert.match(edge, /REPAIR_PROMPT/);
    assert.match(edge, /REPAIR_MAX = 2/);
    assert.match(edge, /gateIncompleteHtml/);
    assert.match(edge, /parseProjectFiles/);
    assert.doesNotMatch(edge, /reasoning_effort/);
    const worker = readFileSync(join(root, "workers/visual/server.mjs"), "utf8");
    assert.match(worker, /MODEL = "grok-build-0.1"/);
    assert.match(worker, /repair max 2/);
    assert.doesNotMatch(worker, /reasoning_effort/);
    const gap = readFileSync(join(root, "src/lib/projects/fase3-gap.ts"), "utf8");
    assert.match(gap, /id: "quality"/);
    assert.match(gap, /planner deterministico/);
    assert.match(gap, /Evaluator su 6 fixture/);
    assert.doesNotMatch(gap, /feature-complete|uguale a Emergent/);
    const overlay = readFileSync(join(root, "src/components/build-overlay.tsx"), "utf8");
    assert.doesNotMatch(overlay, /Officina/);
  });
});
