/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VetrinaRouteImport } from './routes/vetrina'
import { Route as ApiBuildRouteImport } from './routes/api/build'
import { Route as SitoProjectIdRouteImport } from './routes/sito.$projectId'
import { Route as StudioProjectIdRouteImport } from './routes/studio.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetrinaRoute = VetrinaRouteImport.update({
  id: '/vetrina',
  path: '/vetrina',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildRoute = ApiBuildRouteImport.update({
  id: '/api/build',
  path: '/api/build',
  getParentRoute: () => rootRouteImport,
} as any)
const SitoProjectIdRoute = SitoProjectIdRouteImport.update({
  id: '/sito/$projectId',
  path: '/sito/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/studio/$projectId',
  path: '/studio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vetrina': typeof VetrinaRoute
  '/api/build': typeof ApiBuildRoute
  '/sito/$projectId': typeof SitoProjectIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vetrina': typeof VetrinaRoute
  '/api/build': typeof ApiBuildRoute
  '/sito/$projectId': typeof SitoProjectIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vetrina': typeof VetrinaRoute
  '/api/build': typeof ApiBuildRoute
  '/sito/$projectId': typeof SitoProjectIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/vetrina' | '/api/build' | '/sito/$projectId' | '/studio/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/vetrina' | '/api/build' | '/sito/$projectId' | '/studio/$projectId'
  id:
    | '__root__'
    | '/'
    | '/vetrina'
    | '/api/build'
    | '/sito/$projectId'
    | '/studio/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VetrinaRoute: typeof VetrinaRoute
  ApiBuildRoute: typeof ApiBuildRoute
  SitoProjectIdRoute: typeof SitoProjectIdRoute
  StudioProjectIdRoute: typeof StudioProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vetrina': {
      id: '/vetrina'
      path: '/vetrina'
      fullPath: '/vetrina'
      preLoaderRoute: typeof VetrinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build': {
      id: '/api/build'
      path: '/api/build'
      fullPath: '/api/build'
      preLoaderRoute: typeof ApiBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sito/$projectId': {
      id: '/sito/$projectId'
      path: '/sito/$projectId'
      fullPath: '/sito/$projectId'
      preLoaderRoute: typeof SitoProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VetrinaRoute: VetrinaRoute,
  ApiBuildRoute: ApiBuildRoute,
  SitoProjectIdRoute: SitoProjectIdRoute,
  StudioProjectIdRoute: StudioProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
