/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VetrinaRouteImport } from './routes/vetrina'
import { Route as ApiBuildRouteImport } from './routes/api/build'
import { Route as ApiGithubRouteImport } from './routes/api/github'
import { Route as ApiPolishRouteImport } from './routes/api/polish'
import { Route as ApiReleaseRouteImport } from './routes/api/release'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as CondivisoWorkspaceIdRouteImport } from './routes/condiviso.$workspaceId'
import { Route as SitoProjectIdRouteImport } from './routes/sito.$projectId'
import { Route as StudioProjectIdRouteImport } from './routes/studio.$projectId'
import { Route as ApiAppAccessSiteIdRouteImport } from './routes/api/app-access.$siteId'
import { Route as ApiAppDataSiteIdRouteImport } from './routes/api/app-data.$siteId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github.callback'
import { Route as ApiGithubExportRouteImport } from './routes/api/github.export'
import { Route as ApiGithubImportRouteImport } from './routes/api/github.import'
import { Route as ApiGithubReposRouteImport } from './routes/api/github.repos'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs.$id'
import { Route as ApiReleaseIdRouteImport } from './routes/api/release.$id'
import { Route as ApiReleaseCallbackRouteImport } from './routes/api/release.callback'
import { Route as ApiSitesIdRouteImport } from './routes/api/sites.$id'
import { Route as ApiWorkspaceIdRouteImport } from './routes/api/workspace.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VetrinaRoute = VetrinaRouteImport.update({
  id: '/vetrina',
  path: '/vetrina',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildRoute = ApiBuildRouteImport.update({
  id: '/api/build',
  path: '/api/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRoute = ApiGithubRouteImport.update({
  id: '/api/github',
  path: '/api/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolishRoute = ApiPolishRouteImport.update({
  id: '/api/polish',
  path: '/api/polish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleaseRoute = ApiReleaseRouteImport.update({
  id: '/api/release',
  path: '/api/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CondivisoWorkspaceIdRoute = CondivisoWorkspaceIdRouteImport.update({
  id: '/condiviso/$workspaceId',
  path: '/condiviso/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitoProjectIdRoute = SitoProjectIdRouteImport.update({
  id: '/sito/$projectId',
  path: '/sito/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/studio/$projectId',
  path: '/studio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppAccessSiteIdRoute = ApiAppAccessSiteIdRouteImport.update({
  id: '/api/app-access/$siteId',
  path: '/api/app-access/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppDataSiteIdRoute = ApiAppDataSiteIdRouteImport.update({
  id: '/api/app-data/$siteId',
  path: '/api/app-data/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiGithubRoute,
} as any)
const ApiGithubExportRoute = ApiGithubExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiGithubRoute,
} as any)
const ApiGithubImportRoute = ApiGithubImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiGithubRoute,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => ApiGithubRoute,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleaseIdRoute = ApiReleaseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiReleaseRoute,
} as any)
const ApiReleaseCallbackRoute = ApiReleaseCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiReleaseRoute,
} as any)
const ApiSitesIdRoute = ApiSitesIdRouteImport.update({
  id: '/api/sites/$id',
  path: '/api/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceIdRoute = ApiWorkspaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vetrina': typeof VetrinaRoute
  '/api/build': typeof ApiBuildRoute
  '/api/github': typeof ApiGithubRouteWithChildren
  '/api/polish': typeof ApiPolishRoute
  '/api/release': typeof ApiReleaseRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/condiviso/$workspaceId': typeof CondivisoWorkspaceIdRoute
  '/sito/$projectId': typeof SitoProjectIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/app-access/$siteId': typeof ApiAppAccessSiteIdRoute
  '/api/app-data/$siteId': typeof ApiAppDataSiteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/export': typeof ApiGithubExportRoute
  '/api/github/import': typeof ApiGithubImportRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/release/$id': typeof ApiReleaseIdRoute
  '/api/release/callback': typeof ApiReleaseCallbackRoute
  '/api/sites/$id': typeof ApiSitesIdRoute
  '/api/workspace/$id': typeof ApiWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vetrina': typeof VetrinaRoute
  '/api/build': typeof ApiBuildRoute
  '/api/github': typeof ApiGithubRouteWithChildren
  '/api/polish': typeof ApiPolishRoute
  '/api/release': typeof ApiReleaseRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/condiviso/$workspaceId': typeof CondivisoWorkspaceIdRoute
  '/sito/$projectId': typeof SitoProjectIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/app-access/$siteId': typeof ApiAppAccessSiteIdRoute
  '/api/app-data/$siteId': typeof ApiAppDataSiteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/export': typeof ApiGithubExportRoute
  '/api/github/import': typeof ApiGithubImportRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/release/$id': typeof ApiReleaseIdRoute
  '/api/release/callback': typeof ApiReleaseCallbackRoute
  '/api/sites/$id': typeof ApiSitesIdRoute
  '/api/workspace/$id': typeof ApiWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vetrina': typeof VetrinaRoute
  '/api/build': typeof ApiBuildRoute
  '/api/github': typeof ApiGithubRouteWithChildren
  '/api/polish': typeof ApiPolishRoute
  '/api/release': typeof ApiReleaseRouteWithChildren
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/condiviso/$workspaceId': typeof CondivisoWorkspaceIdRoute
  '/sito/$projectId': typeof SitoProjectIdRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/app-access/$siteId': typeof ApiAppAccessSiteIdRoute
  '/api/app-data/$siteId': typeof ApiAppDataSiteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/export': typeof ApiGithubExportRoute
  '/api/github/import': typeof ApiGithubImportRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/release/$id': typeof ApiReleaseIdRoute
  '/api/release/callback': typeof ApiReleaseCallbackRoute
  '/api/sites/$id': typeof ApiSitesIdRoute
  '/api/workspace/$id': typeof ApiWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/vetrina'
    | '/api/build'
    | '/api/github'
    | '/api/polish'
    | '/api/release'
    | '/api/workspace'
    | '/condiviso/$workspaceId'
    | '/sito/$projectId'
    | '/studio/$projectId'
    | '/api/app-access/$siteId'
    | '/api/app-data/$siteId'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/export'
    | '/api/github/import'
    | '/api/github/repos'
    | '/api/jobs/$id'
    | '/api/release/$id'
    | '/api/release/callback'
    | '/api/sites/$id'
    | '/api/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/vetrina'
    | '/api/build'
    | '/api/github'
    | '/api/polish'
    | '/api/release'
    | '/api/workspace'
    | '/condiviso/$workspaceId'
    | '/sito/$projectId'
    | '/studio/$projectId'
    | '/api/app-access/$siteId'
    | '/api/app-data/$siteId'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/export'
    | '/api/github/import'
    | '/api/github/repos'
    | '/api/jobs/$id'
    | '/api/release/$id'
    | '/api/release/callback'
    | '/api/sites/$id'
    | '/api/workspace/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/vetrina'
    | '/api/build'
    | '/api/github'
    | '/api/polish'
    | '/api/release'
    | '/api/workspace'
    | '/condiviso/$workspaceId'
    | '/sito/$projectId'
    | '/studio/$projectId'
    | '/api/app-access/$siteId'
    | '/api/app-data/$siteId'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/export'
    | '/api/github/import'
    | '/api/github/repos'
    | '/api/jobs/$id'
    | '/api/release/$id'
    | '/api/release/callback'
    | '/api/sites/$id'
    | '/api/workspace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  VetrinaRoute: typeof VetrinaRoute
  ApiBuildRoute: typeof ApiBuildRoute
  ApiGithubRoute: typeof ApiGithubRouteWithChildren
  ApiPolishRoute: typeof ApiPolishRoute
  ApiReleaseRoute: typeof ApiReleaseRouteWithChildren
  ApiWorkspaceRoute: typeof ApiWorkspaceRouteWithChildren
  CondivisoWorkspaceIdRoute: typeof CondivisoWorkspaceIdRoute
  SitoProjectIdRoute: typeof SitoProjectIdRoute
  StudioProjectIdRoute: typeof StudioProjectIdRoute
  ApiAppAccessSiteIdRoute: typeof ApiAppAccessSiteIdRoute
  ApiAppDataSiteIdRoute: typeof ApiAppDataSiteIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiSitesIdRoute: typeof ApiSitesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vetrina': {
      id: '/vetrina'
      path: '/vetrina'
      fullPath: '/vetrina'
      preLoaderRoute: typeof VetrinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build': {
      id: '/api/build'
      path: '/api/build'
      fullPath: '/api/build'
      preLoaderRoute: typeof ApiBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github': {
      id: '/api/github'
      path: '/api/github'
      fullPath: '/api/github'
      preLoaderRoute: typeof ApiGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polish': {
      id: '/api/polish'
      path: '/api/polish'
      fullPath: '/api/polish'
      preLoaderRoute: typeof ApiPolishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/release': {
      id: '/api/release'
      path: '/api/release'
      fullPath: '/api/release'
      preLoaderRoute: typeof ApiReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condiviso/$workspaceId': {
      id: '/condiviso/$workspaceId'
      path: '/condiviso/$workspaceId'
      fullPath: '/condiviso/$workspaceId'
      preLoaderRoute: typeof CondivisoWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sito/$projectId': {
      id: '/sito/$projectId'
      path: '/sito/$projectId'
      fullPath: '/sito/$projectId'
      preLoaderRoute: typeof SitoProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-access/$siteId': {
      id: '/api/app-access/$siteId'
      path: '/api/app-access/$siteId'
      fullPath: '/api/app-access/$siteId'
      preLoaderRoute: typeof ApiAppAccessSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-data/$siteId': {
      id: '/api/app-data/$siteId'
      path: '/api/app-data/$siteId'
      fullPath: '/api/app-data/$siteId'
      preLoaderRoute: typeof ApiAppDataSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof ApiGithubRoute
    }
    '/api/github/export': {
      id: '/api/github/export'
      path: '/export'
      fullPath: '/api/github/export'
      preLoaderRoute: typeof ApiGithubExportRouteImport
      parentRoute: typeof ApiGithubRoute
    }
    '/api/github/import': {
      id: '/api/github/import'
      path: '/import'
      fullPath: '/api/github/import'
      preLoaderRoute: typeof ApiGithubImportRouteImport
      parentRoute: typeof ApiGithubRoute
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof ApiGithubRoute
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/release/$id': {
      id: '/api/release/$id'
      path: '/$id'
      fullPath: '/api/release/$id'
      preLoaderRoute: typeof ApiReleaseIdRouteImport
      parentRoute: typeof ApiReleaseRoute
    }
    '/api/release/callback': {
      id: '/api/release/callback'
      path: '/callback'
      fullPath: '/api/release/callback'
      preLoaderRoute: typeof ApiReleaseCallbackRouteImport
      parentRoute: typeof ApiReleaseRoute
    }
    '/api/sites/$id': {
      id: '/api/sites/$id'
      path: '/api/sites/$id'
      fullPath: '/api/sites/$id'
      preLoaderRoute: typeof ApiSitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/$id': {
      id: '/api/workspace/$id'
      path: '/$id'
      fullPath: '/api/workspace/$id'
      preLoaderRoute: typeof ApiWorkspaceIdRouteImport
      parentRoute: typeof ApiWorkspaceRoute
    }
  }
}

interface ApiGithubRouteChildren {
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubExportRoute: typeof ApiGithubExportRoute
  ApiGithubImportRoute: typeof ApiGithubImportRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
}

const ApiGithubRouteChildren: ApiGithubRouteChildren = {
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubExportRoute: ApiGithubExportRoute,
  ApiGithubImportRoute: ApiGithubImportRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
}

const ApiGithubRouteWithChildren = ApiGithubRoute._addFileChildren(
  ApiGithubRouteChildren,
)

interface ApiReleaseRouteChildren {
  ApiReleaseIdRoute: typeof ApiReleaseIdRoute
  ApiReleaseCallbackRoute: typeof ApiReleaseCallbackRoute
}

const ApiReleaseRouteChildren: ApiReleaseRouteChildren = {
  ApiReleaseIdRoute: ApiReleaseIdRoute,
  ApiReleaseCallbackRoute: ApiReleaseCallbackRoute,
}

const ApiReleaseRouteWithChildren = ApiReleaseRoute._addFileChildren(
  ApiReleaseRouteChildren,
)

interface ApiWorkspaceRouteChildren {
  ApiWorkspaceIdRoute: typeof ApiWorkspaceIdRoute
}

const ApiWorkspaceRouteChildren: ApiWorkspaceRouteChildren = {
  ApiWorkspaceIdRoute: ApiWorkspaceIdRoute,
}

const ApiWorkspaceRouteWithChildren = ApiWorkspaceRoute._addFileChildren(
  ApiWorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  VetrinaRoute: VetrinaRoute,
  ApiBuildRoute: ApiBuildRoute,
  ApiGithubRoute: ApiGithubRouteWithChildren,
  ApiPolishRoute: ApiPolishRoute,
  ApiReleaseRoute: ApiReleaseRouteWithChildren,
  ApiWorkspaceRoute: ApiWorkspaceRouteWithChildren,
  CondivisoWorkspaceIdRoute: CondivisoWorkspaceIdRoute,
  SitoProjectIdRoute: SitoProjectIdRoute,
  StudioProjectIdRoute: StudioProjectIdRoute,
  ApiAppAccessSiteIdRoute: ApiAppAccessSiteIdRoute,
  ApiAppDataSiteIdRoute: ApiAppDataSiteIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiSitesIdRoute: ApiSitesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
